### ISSUE TITLE
android emulator from server, accessible from public

### ISSUE THREAD

**Issue by muhkhoi** [NetrisTV/ws-scrcpy#10]
currently i am developing something like remote android through browser with emulated android run on it, while in localhost i am able to control and view to browser, does it possible the browser mirrored to public view?? while trying to access ip from another computer i just cannot make it works

**Comment by muhkhoi** [comment]
i mean just something like forwarding or bridging ws://127.0.0.1:8886/ to accessible from another computer in same network

**Comment by drauggres** [comment]
Hi.
Please look at [scheme](https://github.com/NetrisTV/ws-scrcpy/blob/master/docs/scheme.md) file I've just added.
Basically you need to make available two severs:
1. http server (node js)
2. web-socket server (scrcpy on device/emulator).

By default on android emulators network is configured as NAT, so you will need to forward port to the host machine (as described in [known-issues](https://github.com/NetrisTV/ws-scrcpy#known-issues)

P.S. you may find interesting this project: https://github.com/openstf/stf

**Comment by muhkhoi** [comment]
thanks for the answer, as default run ws://0.0.0.0:8886 or ws://127.0.0.1:8886 as input event and video stream, does it is possible to birdge websocket to public ip, so my computer able to accessed by another in same local ip?

**Comment by drauggres** [comment]
[known-issues](https://github.com/NetrisTV/ws-scrcpy#known-issues):
> The server on the Android Emulator listens on internal interface and not available from the outside (as workaround you can do `adb forward tcp:8886 tcp:8886`)

**Comment by muhkhoi** [comment]
> [known-issues](https://github.com/NetrisTV/ws-scrcpy#known-issues):
> 
> > The server on the Android Emulator listens on internal interface and not available from the outside (as workaround you can do `adb forward tcp:8886 tcp:8886`)
adb forward tcp:8886 tcp:8886, enable server accessible to 127.0.0.1:8886, but my aim is to assign to public ip like (192.168.xxx.xxx:8886) does it is possible? sorry i'm pretty new in android development

**Comment by muhkhoi** [comment]
my aims is just like forward to public ip (192.168.xx.xx) instead on localhost (127.0.0.1)
