### ISSUE TITLE
port forward wda url to localport using usbmuxd

### ISSUE THREAD

**Issue by tulasikrishan89** [NetrisTV/ws-scrcpy#100]
**Enhancement request:** 

using device url will not work in proxy environment.

With port forward - the wda url will socket to local port, so wda commands can be sent to http://localhost:localPort 

iproxy localPORT devicePort -s 0.0.0.0 -u $UDID

**Comment by drauggres** [comment]
1. WebDriverAgent is no longer started by `ws-qvh`, now node-server runs it
2. WDA port is already being forwarded

https://github.com/NetrisTV/ws-scrcpy/blob/master/src/server/appl-device/services/WDARunner.ts

**Comment by tulasikrishan89** [comment]
Must be something wring then. It is touch is not working in proxy environment, only video is working. Turning off the vpn is the only solution to touch to work
