### ISSUE TITLE
listen to keyboard event in browser and sent to device

### ISSUE THREAD

**Issue by krishtoautomate** [NetrisTV/ws-scrcpy#101]
enhancement request to listen to keyboard event in browser and sent to device

POST: {{DEVICE_URL}}/session/{{SESSSION_ID}}/wda/keys
BODY: {"value":["test"],"frequency":120}

**Comment by drauggres** [comment]
`ws-qvh` now responsible only for video stream.

**Comment by drauggres** [comment]
I don't think it is possible to use `/wda/keys` to capture events same way as `Capture keyboard` on android/scrcpy.
But it can be used as `Send as keys` feature, i.e. you will need to type text into `input`/`textarea` and then press button.
On android/scrcpy this is implemented here:
https://github.com/NetrisTV/ws-scrcpy/blob/67cc51c90861cadd1f977f14bc3efe8b5dfa56ca/src/app/googDevice/toolbox/DroidMoreBox.ts#L35-L45

For ios/wda you might want to look at:
- https://github.com/NetrisTV/ws-scrcpy/blob/master/src/app/applDevice/toolbox/QVHackMoreBox.ts
- https://github.com/NetrisTV/ws-scrcpy/blob/master/src/app/applDevice/WdaConnection.ts
- https://github.com/NetrisTV/ws-scrcpy/blob/master/src/server/appl-device/services/WDARunner.ts

**Comment by tulasikrishan89** [comment]
possible : 
1. listen to each keydown from browser listener
2. call wda/keys api for each key by sending body each keyword they user is clicking

**Comment by drauggres** [comment]
See https://github.com/NetrisTV/ws-scrcpy/pull/188

Not exactly what you asked for, but this way it works with non ASCII symbols.
