### ISSUE TITLE
multiple servers and single client

### ISSUE THREAD

**Issue by krishtoautomate** [NetrisTV/ws-scrcpy#103]
possible access and control devices from multiple host.

1. run ws-scrcpy in multiple machines
2. mention host names in one of the config file of the main machine and run ws-scrcpy

**Comment by drauggres** [comment]
https://github.com/NetrisTV/ws-scrcpy#run-configuration

**Comment by krishtoautomate** [comment]
```
export interface HostItem {
    type: 'android' | 'ios';
    secure: false;
    hostname: $HOST_ADDRESS;
    port: $HOST_PORT;
    useProxy?: false;
}

export interface Configuration {
    runApplTracker?: true;
    announceApplTracker?: true;
    runGoogTracker?: true;
    announceGoogTracker?: true;
    hostList?: HostItem[];
}
```
please help me correct!

what is hostList?: HostItem[];  ?

**Comment by drauggres** [comment]
Something like this:
```javascript
{
  "runGoogTracker": true,
  "hostList": [
    {
      "type": "android",
      "secure": false,
      "hostname": "192.168.1.128",
      "port": "8000"
    },
    {
      "type": "ios",
      "secure": false,
      "hostname": "192.168.1.128",
      "port": "8000",
      "useProxy": true
    }
  ]
}
```

**Comment by krishtoautomate** [comment]
so i can add as many hosts as possible.

but why i need to add only "runGoogTracker": true.
What about ios?

**Comment by krishtoautomate** [comment]
instructions are not clean enough.

saved below content to 'Configuration.d.ts' file

`export interface HostItem {
    type: 'android';
    secure: false;
    hostname: 192.168.0.159;
    port:  8000;
    useProxy?: false;
}

export interface Configuration {
    runApplTracker?: true;
    announceApplTracker?: true;
    runGoogTracker?: true;
    announceGoogTracker?: true;
    hostList?: HostItem[
    {
      "type": "android",
      "secure": false,
      "hostname": "192.168.0.159",
      "port": "8000"
    },
    {
      "type": "ios",
      "secure": false,
      "hostname": "192.168.0.159",
      "port": "8000",
      "useProxy": true
    }
  ]
}
`

did below start process:

`export WS_SCRCPY_CONFIG=/Users/User/Downloads/Configuration.d.ts
npm start`


I dont see the devices connected to other host

**Comment by krishtoautomate** [comment]
Failed to load configuration from file "/Users/User/Downloads/Configuration.d.ts"
Error: Unexpected token e in JSON at position 0

**Comment by krishtoautomate** [comment]
works perfect. can you please update the readme file as

save in json file and set 

export WS_SCRCPY_CONFIG=$PATH_TO_CONFIG_FILE/Configuration.json
 npm start

**Comment by krishtoautomate** [comment]
but why i need to add only "runGoogTracker": true.
What about ios?

https://github.com/NetrisTV/ws-scrcpy/issues/103#issuecomment-853803499
