### ISSUE TITLE
Black screen for android 12 beta in pixel device

### ISSUE THREAD

**Issue by krishtoautomate** [NetrisTV/ws-scrcpy#107]
Android 12 beta is showing black screen in pixel device.

Please refer to bug, it might help to add a patch here. thanks

https://github.com/Genymobile/scrcpy/issues/2129

**Comment by drauggres** [comment]
https://github.com/Genymobile/scrcpy/issues/2129#issuecomment-859372566

**Comment by drauggres** [comment]
I tried scrcpy v1.18 and was not able to stream screen from android emulator with Android 12 beta.

**Comment by krishtoautomate** [comment]
i tired this repo and it is working: https://github.com/me-abhishekpal/scrcpy-quickfix-secure-flag-MacOS.git

**Comment by krishtoautomate** [comment]
scrcpy 1.19 got the fix for this issue

**Comment by krishtoautomate** [comment]
./server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java



```
 private static IBinder createDisplay() {
        // Since Android 12 (preview), secure displays could not be created with shell permissions anymore.
        // On Android 12 preview, SDK_INT is still R (not S), but CODENAME is "S".
        boolean secure = Build.VERSION.SDK_INT < Build.VERSION_CODES.R || (Build.VERSION.SDK_INT == Build.VERSION_CODES.R && !"S"
                .equals(Build.VERSION.CODENAME));
        return SurfaceControl.createDisplay("scrcpy", secure);
    }
```
