### ISSUE TITLE
https://github.com/drauggres/scrcpy/releases/download/v1.8.1/scrcpy-server.jar not found

### ISSUE THREAD

**Issue by lljxx1** [NetrisTV/ws-scrcpy#11]
https://github.com/drauggres/scrcpy/releases/download/v1.8.1/scrcpy-server.jar not found

**Comment by drauggres** [comment]
@lljxx1 Sorry about that, I moved the repo to [NetrisTV/scrcpy](https://github.com/NetrisTV/scrcpy).
Now it s should be fine.
