### ISSUE TITLE
how to debug with this project?

### ISSUE THREAD

**Issue by GreenHand-zmy** [NetrisTV/ws-scrcpy#120]

**Comment by drauggres** [comment]
### Client

1. build dev version (will include source maps):
> npm run dist:dev

2. run from `dist` directory:
> node start

3. for debugging I use browser's built-in dev tools, but you also can use your favorite IDE

### Node.js server

1. `npm run dist:dev`
2. `cd dist`
3. `node --inspect-brk ./index.js`

Also you might want to set `DEBUG` environment variable to `*` ([debug](https://github.com/visionmedia/debug)):
> DEBUG=* node  --inspect-brk ./index.js

### Android server (`scrcpy-server.jar`)

Source code is available [here](https://github.com/NetrisTV/scrcpy/tree/feature/websocket-v1.17.x)
You might want to build dev version.
To debug server:
1. start node server
2. kill server from UI (click button with cross and PID number).
3. upload server package to a device:
> adb push server/build/outputs/apk/debug/server-debug.apk /data/local/tmp/scrcpy-server.jar

4. setup port forwarding:
> adb forward tcp:5005 tcp:5005

5. connect to device with adb shell:
> adb shell

6.1. for Android 8 and below run this in adb shell (single line):
> CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process -agentlib:jdwp=transport=dt_socket,suspend=y,server=y,address=5005 / com.genymobile.scrcpy.Server 1.17-ws5 DEBUG web 8886

6.2. for Android 9 and above:
>  CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process -XjdwpProvider:internal -XjdwpOptions:transport=dt_socket,suspend=y,server=y,address=5005 / com.genymobile.scrcpy.Server 1.17-ws5 web DEBUG 8886

7. Open project (scrcpy, not ws-scrcpy) in Android Studio, create `Remote` Debug configuration with:
> Host: localhost, Port: 5005

Now you should be able to connect debugger to the remote server on the device.

**Comment by lilie008** [comment]
About debug Android server (scrcpy-server.jar),how to solve this?
![image](https://user-images.githubusercontent.com/6621971/140011769-3eea53bb-e53a-4d7f-90c3-507f749d177e.png)
![image](https://user-images.githubusercontent.com/6621971/140011914-ab63b98e-268b-47ea-b62e-1456c6ba10c2.png)

**Comment by drauggres** [comment]
Hi.
You have to start the server manually. See p6 in the [documentation](https://github.com/NetrisTV/ws-scrcpy/blob/4d2c7f60ab249e0a55cc8c4e1d5da40c02251f8c/docs/debug.md#android-server-scrcpy-serverjar).
In the latest version it should look like this (see [this](https://github.com/NetrisTV/ws-scrcpy/blob/4d2c7f60ab249e0a55cc8c4e1d5da40c02251f8c/src/common/Constants.ts)):
> CLASSPATH=[..] / com.genymobile.scrcpy.Server 1.19-ws1 web ERROR 8886 true

You should do it before you start `ws-scrcpy` or kill the server started by it from the UI (see p2).

**Comment by lilie008** [comment]
> Hi. You have to start the server manually. See p6 in the [documentation](https://github.com/NetrisTV/ws-scrcpy/blob/4d2c7f60ab249e0a55cc8c4e1d5da40c02251f8c/docs/debug.md#android-server-scrcpy-serverjar). In the latest version it should look like this (see [this](https://github.com/NetrisTV/ws-scrcpy/blob/4d2c7f60ab249e0a55cc8c4e1d5da40c02251f8c/src/common/Constants.ts)):
> 
> > CLASSPATH=[..] / com.genymobile.scrcpy.Server 1.19-ws1 web ERROR 8886 true
> 
> You should do it before you start `ws-scrcpy` or kill the server started by it from the UI (see p2).

Thanks Reply.

step1
I replaced the scrcpy-server.jar with my code and start `ws-scrcpy`,then
the source code on the node side will push `vendor/Genymobile/scrcpy-server.jar` automatically to the phone with `CLASSPATH=/data/local/tmp/scrcpy-server.jar nohup app_process / com.genymobile.scrcpy.Server 1.19-ws1 web ERROR 8886 true 2>&1 > /dev/null`.

step2
I killed the process server like this:
`netstat -nlp | grep 8886
kill -9 port`

step3
Open android studio remote and run start.

I will try it.Thanks again.

**Comment by drauggres** [comment]
> step2
> I killed the process server like this:
> `netstat -nlp | grep 8886 kill -9 port`

If you kill it like this, node-server will restart it. You need to kill it from the UI.

After that you need to manually push your modified `scrcpy-server.jar` to a device and run it with a command from [p6](https://github.com/NetrisTV/ws-scrcpy/blob/4d2c7f60ab249e0a55cc8c4e1d5da40c02251f8c/docs/debug.md#android-server-scrcpy-serverjar).

Than you will be able to use `Remote` debug configuration in the Studio to connect to the process.

**Comment by lilie008** [comment]
I'm a node beginners.I don't understand what‘s the UI refers to?Could u please tell me  more details.

**Comment by drauggres** [comment]
> I don't understand what‘s the UI refers to?

User Interface. In the web page you can find the process identifier (PID) of `scrcpy-server.jar`. To kill the process you need to click the button with PID.

![image](https://user-images.githubusercontent.com/7796592/140071299-3e6d92c9-6a42-4507-9d97-99dd70ebdf79.png)
