### ISSUE TITLE
using ws-scrcpy in another project

### ISSUE THREAD

**Issue by sauravbv** [NetrisTV/ws-scrcpy#121]
Is there a way to use ws-scrcpy in another project like angular. Current way I am doing is via an iframe but cross communication between host and ws-scrcpy won't be possible.

**Comment by drauggres** [comment]
There is no any framework specific code in this project. And I didn't plan it to be integratable.
So you will probably need to take necessary parts from the code and rewrite them in angular-way.

**Comment by sauravbv** [comment]
Thank you.
