### ISSUE TITLE
Possible to use bluetooth control for click, swipe, enter text for ios

### ISSUE THREAD

**Issue by krishtoautomate** [NetrisTV/ws-scrcpy#122]
Possible to use bluetooth control for click, swipe, enter text for ios instead of WebDriveragent.

I see Wormhole and vysor are using bluetooth as means of communication with ios devices and It looks more affective and smooth.

References: 
https://bluetooth-keyboard.com/
wormhole
vysor

**Comment by gotoin** [comment]
+1

**Comment by krishtoautomate** [comment]
Mac removed this feature starting monterary macos. 
May this can be possible with linux.

**Comment by gotoin** [comment]
@krishtoautomate or windows

**Comment by krishtoautomate** [comment]
Yes possible but not stable due to limitation with number of connections, works well for 1-2 devices
