### ISSUE TITLE
How to use the keyboard wasd to control the direction of the game

### ISSUE THREAD

**Issue by mannysys** [NetrisTV/ws-scrcpy#123]
How to use the keyboard `wasd` to control the direction of the game

**Comment by drauggres** [comment]
Hi.

You can enable `Capture keyboard` by clicking corresponding button in the controls.
Here is the code responsible for keyboard events:
https://github.com/NetrisTV/ws-scrcpy/blob/0dc4ea887aa404326ba61d0c5e07c16df18c2431/src/app/googDevice/client/StreamClientScrcpy.ts#L349-L359

`setHandleKeyboardEvents` is called when you click `Capture keyboard`.
`onKeyEvent` is called when you press/release button on you keyboard.

The answer to you question will depend on how you can control the direction from physical device?
Maybe it will be enought to remap `wasd` to arrows or maybe you will need to send [`TouchControlMessage`s](https://github.com/NetrisTV/ws-scrcpy/blob/0dc4ea887aa404326ba61d0c5e07c16df18c2431/src/app/controlMessage/TouchControlMessage.ts) instead.

**Comment by mannysys** [comment]
> 

- [

1. 

- [ ] 

- [ ] 

](url)

**Comment by mannysys** [comment]
thank you very much @drauggres
