### ISSUE TITLE
In the version of v1.9, what's the keycode for all SELECT_ALL

### ISSUE THREAD

**Issue by yjzzcao** [NetrisTV/ws-scrcpy#13]
In the version of v1.9, what's the keycode for SELECT_ALL

we find the CUT & COPY & PASTE, but not SELECT_ALL

**Comment by drauggres** [comment]
Don't think that this question is relevant for this project.

Anyway, all keycodes for Android are [here](https://android.googlesource.com/platform/frameworks/native/+/master/include/android/keycodes.h)
There is no special keycode for `SELECT_ALL`.

You can try to use use `CTRL+A` combination like this:
```javascript
const eventDown = new KeyCodeControlEvent(KeyEvent.ACTION_DOWN, KeyEvent.KEYCODE_A, KeyEvent.META_CTRL_ON);
const eventUp = new KeyCodeControlEvent(KeyEvent.ACTION_UP, KeyEvent.KEYCODE_A, KeyEvent.META_CTRL_ON);
```
More information about KeyEvent in [official documentation](https://developer.android.com/reference/android/view/KeyEvent.html)
