### ISSUE TITLE
Response to mouse middle button scrolling?

### ISSUE THREAD

**Issue by aaron1028923** [NetrisTV/ws-scrcpy#133]
Any way to use the middle button scrolling?

**Comment by drauggres** [comment]
Hi. At the moment I handle only these events:
https://github.com/NetrisTV/ws-scrcpy/blob/552bbfc8c4e7ebac494a7b9b152b08ca01621c03/src/app/touchHandler/FeaturedTouchHandler.ts#L15-L23

Browsers have [`onwheel`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onwheel) event. We can handle it and send a [`ScrollControlMessage`](https://github.com/NetrisTV/ws-scrcpy/blob/552bbfc8c4e7ebac494a7b9b152b08ca01621c03/src/app/controlMessage/ScrollControlMessage.ts#L10-L15) to a device.
