### ISSUE TITLE
Scroll bar invalid

### ISSUE THREAD

**Issue by zhoupuzeng** [NetrisTV/ws-scrcpy#135]
The Android device size method scroll bar is invalid because absolute positioning is used,

**Comment by zhoupuzeng** [comment]
![image](https://user-images.githubusercontent.com/74239498/131471593-e804242c-fbf6-4c82-956a-32b6eaa90115.png)
The requirement is for the scroll bar to move, unfortunately it's out of the document flow

**Comment by zhoupuzeng** [comment]
Changing to relative positioning will cause click misalignment

**Comment by drauggres** [comment]
Hi.
There is no scroll bars in current version. I guess you changed something.  Can you share you modifications? Otherwise I can't help you.

Probably the problem is here (only `html` tag scrolling is taken into account):
https://github.com/NetrisTV/ws-scrcpy/blob/7e13d6269c451c1e9470e86d3c45ee3db6bb05d9/src/app/touchHandler/TouchHandler.ts#L212-L218

**Comment by zhoupuzeng** [comment]
![image](https://user-images.githubusercontent.com/74239498/131494671-53f2857c-5af0-44a8-b849-aceeed992b47.png)
We need users to be able to change the size of the device, but they may scroll out of the screen, so I wrote a relative positioning for the outer container so that they can scroll. Unfortunately, it will lead to the wrong click position of the device

**Comment by zhoupuzeng** [comment]
![image](https://user-images.githubusercontent.com/74239498/131498081-24a997e3-eb9c-4dc6-8050-46b148a1f0c6.png)
![image](https://user-images.githubusercontent.com/74239498/131498153-1e66de5b-6552-4443-8634-858527805d63.png)
In the first picture, I wrote that relative positioning can be scrolled but will lead to click position offset. In the second picture, I turned off relative positioning and the scroll bar is invalid. How can I scroll and click without offset

**Comment by drauggres** [comment]
Can you try to replace code above with this:
```typescript

        const { width, height } = screenInfo.videoSize;
        const target: HTMLElement = e.target as HTMLElement;
        const rect = target.getBoundingClientRect();
        let { clientWidth, clientHeight } = target;
        let touchX = e.clientX - rect.left;
        let touchY = e.clientY - rect.top;
```

**Comment by zhoupuzeng** [comment]
The above problem has been solved. Thank you very much. How to increase the clarity of Java side transmission？

**Comment by drauggres** [comment]
> How to increase the clarity of Java side transmission？

What do you mean? Video quality?

**Comment by zhoupuzeng** [comment]
Hi ,We want the picture quality transmitted by java to reach the video stream equal to the quality of mobile screen capture

**Comment by drauggres** [comment]
See https://github.com/NetrisTV/ws-scrcpy/discussions/139
