### ISSUE TITLE
the video in web is  so blurred

### ISSUE THREAD

**Issue by huangqichao** [NetrisTV/ws-scrcpy#14]
the video in web is  so blurred,how to make it clearer?

**Comment by drauggres** [comment]
1. Click `► Change video settings`.
2. Increase `Bitrate` 
3. Click `Change video settings` button

**Comment by huangqichao** [comment]
thank you! this is a great project!
i wan't to use the native decode module in my project, should i change the scrcpy.jar code? or use the official jar is fine ?

**Comment by drauggres** [comment]
Thanks.
You will need to use [this fork](https://github.com/NetrisTV/scrcpy/tree/feature/websocket-v1.9).
Or you can try to combine official scrcpy with https://github.com/novnc/websockify (I haven't try this)

**Comment by huangqichao** [comment]
my current data stream flows like openstf's png stream：phone video socket  ->node server ->node websocket server -> web websocket client，the problem is the .h264 stream can't not decoded and played well in html, so i want to use your  native decoder to play the data stream from official scrcpy，is that fine？

**Comment by drauggres** [comment]
You should probably use https://github.com/xevojapan/h264-converter directly: "native decoder" is just a simple wrapper-class around it.

**Comment by huangqichao** [comment]
Hi, i hava another problem. When i increase the bitrate of phone video, like 4000000 or 8000000,the video will stop playing after some seconds,the stream data is ok and the h264-converter log keep printing,but the video frame stop playing.  This problem came out easily on some old computer.Do you have any idea about this?

**Comment by drauggres** [comment]
In case you didn't know: you can setup logger for h264-converter like this:
```typescript
import VideoConverter, { setLogger } from 'h264-converter';

setLogger(console.log, console.error);
```
I don't think I can help you with this any further: I don't have knowledge about `h264-converter`s internals.

**Comment by huangqichao** [comment]
I have setup logger but the outputs seems to be normal。Thank you anyway, ws-scrcpy is a very helpful project,good job！

**Comment by drauggres** [comment]
> the video will stop playing after some seconds,the stream data is ok and the h264-converter log keep printing,but the video frame stop playing. 

Solved by https://github.com/NetrisTV/ws-scrcpy/commit/36226efa7f467ae26388d70636e83b8e67b653c3
