### ISSUE TITLE
Hi.

### ISSUE THREAD

**Issue by changmiao007** [NetrisTV/ws-scrcpy#140]
I've seen all the setup related codes here. The video quality still can not meet our requirements. We have set the Java end to send the video stream according to the maximum resolution of the mobile phone, and set the video frame to a fixed size at the front end, but this can only slightly increase the definition, and can not solve the video clarity from the source

**Comment by drauggres** [comment]
See https://github.com/NetrisTV/ws-scrcpy/discussions/139.
Please, send your replies there.
