### ISSUE TITLE
ws-scrcpy 配套的 java 端开源吗?

### ISSUE THREAD

**Issue by changmiao007** [NetrisTV/ws-scrcpy#142]
你好，问一下，ws-scrcpy 配套的 java 端开源吗? 我尝试过用， 用 scrcpy 项目下的 java端 .jar 替换 ws-scrcpy 的项目里的java 结果报错，提示不是 17.5-ws 版本，我修改ts端代码，结果还有其他报错，你能给一份 ws-scrcpy 配套的java代码吗？

**Comment by drauggres** [comment]
https://github.com/NetrisTV/ws-scrcpy#scrcpy-websocket-fork

**Comment by changmiao007** [comment]
thanks very much,I'm trying to get clearer video quality without compressing the video stream on the Java side. I don't know if you have any better suggestions, but how to compile the Java source code provided by you in Android studio is a challenge for me.

**Comment by drauggres** [comment]
> how to compile the Java source code provided by you in Android studio is a challenge for me.

https://github.com/NetrisTV/scrcpy/blob/feature/websocket-v1.17.x/BUILD.md

or 

> ./gradlew build

or

![image](https://user-images.githubusercontent.com/7796592/132101834-528f3fcc-97c7-4f5a-86ec-a6c55fc78c8f.png)

Result will be under `server/build/outputs/apk/[release|debug]`. You should rename the file to `scrcpy-server.jar`.

**Comment by changmiao007** [comment]
thanks very much.

**Comment by changmiao007** [comment]
thanks very much.

**Comment by changmiao007** [comment]
thanks very much.

**Comment by changmiao007** [comment]
![image](https://user-images.githubusercontent.com/89907354/132151647-90e2bb9d-a289-428a-a6cc-52caa33b23e9.png)

**Comment by changmiao007** [comment]
![image](https://user-images.githubusercontent.com/89907354/132151995-35614217-9230-4dcd-b900-602e5f3c82c2.png)

**Comment by drauggres** [comment]
> and pushed it to my mobile phone

You should have put it in `dist/vendor/Genymobile/scrcpy/` (or `vendor/Genymobile/scrcpy/` and rebuild the project). Ws-scrcpy will push it to device by itself.

**Comment by changmiao007** [comment]
Beautiful, that's what I did, ha ha
