### ISSUE TITLE
How to get a clearer video stream？

### ISSUE THREAD

**Issue by changmiao007** [NetrisTV/ws-scrcpy#145]
We want to get a clearer video stream than H264. Do you have any new scheme？
![image](https://user-images.githubusercontent.com/89907354/132435720-d9749571-eb31-45f6-915d-8f25b139368e.png)

**Comment by changmiao007** [comment]
Or can we adjust a parameter so that H264 can play the original image quality directly without compression?

**Comment by drauggres** [comment]
> Do you have any new scheme？

No. I already described all options in https://github.com/NetrisTV/ws-scrcpy/discussions/139.

> Or can we adjust a parameter so that H264 can play the original image quality directly without compression?

You can try to play with [codec options](https://github.com/Genymobile/scrcpy/commit/080a4ee3654a9b7e96c8ffe37474b5c21c02852a) as well (be aware that Broadway and TinyH264 support only Baseline profile https://github.com/NetrisTV/ws-scrcpy/issues/70).
What screen resolution does the phone have and what video settings did you apply?

**Comment by changmiao007** [comment]
All the options have been optimized, but we still want to further improve the video quality. It's best to force H264 to send I-frames every time without compressing the image quality, so as to achieve the optimal definition, but I don't see the corresponding parameters for controlling I-frames provided by the Java side.

![image](https://user-images.githubusercontent.com/89907354/132612655-336a9b41-e1e4-43a6-882e-d9d944e174fd.png)

![image](https://user-images.githubusercontent.com/89907354/132612793-016f6746-10c7-481b-a12d-5b992db439b5.png)

**Comment by drauggres** [comment]
Something is clearly wrong, if you applied  max size `20000x20000`, but received `400x832` image.
Are you sure you clicked the `Change video settings` button after changing the values?

**Comment by changmiao007** [comment]
![image](https://user-images.githubusercontent.com/89907354/133578490-d65cc05f-9804-4545-9312-4cf446d2a96c.png)
Can you set different encoders to encode video here? Can you give me an example? The encoders I filled in the system failed.

**Comment by drauggres** [comment]
You can select encoder from the field below (it is conveniently labeled as "Encoder").
Only AVC encoders are supported:
https://github.com/Genymobile/scrcpy/blob/a846c01883e15cbf04ec2c76c07c7e0f074306b2/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L159-L168
