### ISSUE TITLE
Only works with localhost

### ISSUE THREAD

**Issue by rohankudale** [NetrisTV/ws-scrcpy#15]
When Android device is not connected to internet and adb forward is done(as recommended workaround), Does not work with system IP only works with local host. "ERR_CONNECTION_REFUSED" is received in browser

**Comment by drauggres** [comment]
[Scheme](https://github.com/NetrisTV/ws-scrcpy/blob/master/docs/scheme.md).

- You don't need to use `adb forward` for real device then `Client` is in the same network with it.
- The `adb` server on your `Server` host listens only on the local interface.
- If your `Client` and `device` are in different networks (i.e. you want to access your device from the Internet) you will need to additionally setup port forwarding on `Server` from local interface to public.

**Comment by rohankudale** [comment]
Thank you for the response.
port forwarding from local to public should work but it seems like extra overhead. I want data at public port directly instead of local.

To further clarify. 
- My mobile device will not be connected to internet. communication between android and server has to happen through USB only.

- I Hardcoded IP parameter in ServerDeviceConnection.ts to localhost. After doing this its working correctly on localhost. I want to access the same from different machine through IP which is giving the error I mentioned before.

**Comment by drauggres** [comment]
As I mentioned, by default adb server listens only on local interface, so all ports are forwared to local interface also. You can try [this](https://stackoverflow.com/questions/56130335/adb-port-forwarding-to-listen-on-all-interfaces) instead (not sure if this works).

**Comment by rohankudale** [comment]
Its working. Thanks for sharing the link
