### ISSUE TITLE
The Safari and chrome browsers of IOS phones do not display Android

### ISSUE THREAD

**Issue by zoe-21** [NetrisTV/ws-scrcpy#159]
Hello, I'm operating Android in safari or Chrome browse
![Android](https://user-images.githubusercontent.com/74239498/140256817-f37aed4f-c205-4c4f-b757-e6bf323696dd.jpg)
r on IOS real machine. It doesn't display. What's the solution

**Comment by drauggres** [comment]
Hi. That does not look like my project. What's in your screenshot?

**Comment by drauggres** [comment]
Oh, I remembered the issue you opend a couple months ago.

What decoder/player do you use in your project? All `Player` classes have static method `isSupported`, you can use it to check if this player will work in the current browser.

If I recall correctly, safari on iOS before 15 does not support MSE (and chrome on iOS is just a wrapper for safari).
https://github.com/NetrisTV/ws-scrcpy/blob/4d2c7f60ab249e0a55cc8c4e1d5da40c02251f8c/src/app/player/MsePlayer.ts#L72-L74

**Comment by zhoupuzeng** [comment]
Hello, I tried MSE in IOS 15.1, but there is no support. Why

**Comment by drauggres** [comment]
> Hello, I tried MSE in IOS 15.1, but there is no support. Why

I was wrong. It works on iPads with iPadOS 13+, but doesn't work on iPhones (Safari limitation from the Apple side, not mine): https://caniuse.com/mediasource.

Use other decoder/player, broadway.js should do fine on iOS.

**Comment by zhoupuzeng** [comment]
Ha ha, yes, but the resolution of broadway.jsis not very good. Do you have any solutions

**Comment by drauggres** [comment]
> but the resolution of broadway.jsis not very good

What do you mean? For broadway.js I have "conservative" default video-settings, but you can change them at any time.

> Do you have any solutions

Everything I have is included in this project. In theory, it should be possible to wrap video into HLS-stream (every apple device supports it), but I haven't tried it. Also hls-stream, probably, will have significant lag.

**Comment by zhoupuzeng** [comment]
Hello, the mobile terminal displays normally at present. We hope to operate the remote device in the mobile browser and support full screen operation. We tried the full screen API of JS, which does not support Safari of IOS. Do you have a full screen solution for mobile terminals (able to delete the address bar and toolba
![1f60f6814ffcc5fa83066b14afc2d69](https://user-images.githubusercontent.com/74239498/143193357-3ac3cb0a-eeb7-4e40-84e3-969065dbcd42.jpg)
r)

**Comment by zhoupuzeng** [comment]
Ask again, do you have a solution for real-time audio transmission from remote devices to current physical devices

**Comment by drauggres** [comment]
> Hello, the mobile terminal displays normally at present. 

Hi. It's good to know.

> We hope to operate the remote device in the mobile browser and support full screen operation. We tried the full screen API of JS, which does not support Safari of IOS. Do you have a full screen solution for mobile terminals (able to delete the address bar and toolbar)

I don't really use this project from a mobile device too often and I didn't spend much time on learning mobile web development.
As far as I know, you can't hide them completely. Swipe from the top or scrolling to the top will bring them back. Look [here](https://stackoverflow.com/questions/6011223/how-to-completely-hide-the-navigation-bar-in-iphone-html5), it is pretty old, but should still work.

P.S. As an alternative solution you can create a simple application with only WebView in it.
P.P.S About audio see [here](https://github.com/NetrisTV/ws-scrcpy/discussions/38).

**Comment by zhoupuzeng** [comment]
Hi, we are developing IOS audio. Do you have a solution? Whether there is a source code reference.

**Comment by drauggres** [comment]
Hi. 
For the client see the link in the previous message (and maybe [this](https://github.com/GoogleChromeLabs/web-audio-samples) will be useful).
For the server see:
https://github.com/NetrisTV/ws-qvh/blob/a9a487ad1da187b0fa40b7888907f3e93d34fc35/naluwriter.go#L37
and
https://github.com/danielpaulus/quicktime_video_hack/blob/7067c1d42ac6fa69c6e8ded5d3eb993affb895eb/screencapture/coremedia/avfilewriter.go#L86
