### ISSUE TITLE
Anything not display in webbrowser

### ISSUE THREAD

**Issue by BlackINT3** [NetrisTV/ws-scrcpy#160]
I caught the exception from scrcpy-server.jar

4286  4307 E scrcpy  : WebSocket error
4286  4307 E scrcpy  : java.lang.IndexOutOfBoundsException: Index: 8, Size: 1
4286  4307 E scrcpy  :      at java.util.ArrayList.add(ArrayList.java:483)
4286  4307 E scrcpy  :      at com.genymobile.scrcpy.WebSocketConnection.getInitialInfo(WebSocketConnection.java:130)
4286  4307 E scrcpy  :      at com.genymobile.scrcpy.WSServer.onOpen(WSServer.java:78)
4286  4307 E scrcpy  :      at org.java_websocket.server.WebSocketServer.onWebsocketOpen(WebSocketServer.java:654)
4286  4307 E scrcpy  :      at org.java_websocket.WebSocketImpl.open(WebSocketImpl.java:717)
4286  4307 E scrcpy  :      at org.java_websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:288)
4286  4307 E scrcpy  :      at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:221)
4286  4307 E scrcpy  :      at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1011)
4286  4307 E scrcpy  :      at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:993)

**Comment by BlackINT3** [comment]
![image](https://user-images.githubusercontent.com/35478470/141431683-751a5d5d-e9c0-4d0e-8597-c6c2e38f6596.png)

**Comment by drauggres** [comment]
Hi. FYI the server source code is also open: https://github.com/NetrisTV/scrcpy/blob/feature/websocket-server/server/src/main/java/com/genymobile/scrcpy/WebSocketConnection.java#L130

If you want to dig into it yourself, here is the info about debugging: https://github.com/NetrisTV/ws-scrcpy/blob/master/docs/debug.md

Looks like `displayId` are not continuously increasing numbers as I thought (you have `0` and `8`).

**Comment by BlackINT3** [comment]
thanks, i try it right now.
