### ISSUE TITLE
The screen display frame loss.

### ISSUE THREAD

**Issue by BlackINT3** [NetrisTV/ws-scrcpy#162]
the screen display frame loss usually as below and i have to reboot the device.

device: pixel 1

![image](https://user-images.githubusercontent.com/35478470/142396596-47a23d1e-00e9-445c-bade-7b8daf840f9d.png)
![image](https://user-images.githubusercontent.com/35478470/142398439-4179d53b-de7d-413b-84cb-4f9e0900a40d.png)

**Comment by drauggres** [comment]
What decoder/player did you use?
What happens if you change video width/height (inside "three dots" menu)?

Also changing **en**coder could help (use `Configure stream`).

PS. FYI, there is dedicated a button for taking a screenshot (it will save current picture from the "video").

**Comment by BlackINT3** [comment]
decorder: Broadway.js ，also others not work.

it works as refresh the pages or stream configured, but frame-loss again as well touch for a while.

**Comment by drauggres** [comment]
It really looks like lost frames, but we use WebSockets (i.e. TCP and we can't lose a packet) and never drop undecoded frames (unless we receive I-frame).

Have you tried a different encoder?
What about original scrcpy, does it work with this device?
