### ISSUE TITLE
Using https results in no devices listed in web client

### ISSUE THREAD

**Issue by MarkusPint** [NetrisTV/ws-scrcpy#164]
I configured a SSL cert using the certPath and keyPath variables. The web client is served from https correctly and websockets seem to be using the "wss" protocol.

However, the web client doesn't list any devices. When I disable https, devices are listed again.

**Comment by drauggres** [comment]
Hi. Can you post your config file?

**Comment by MarkusPint** [comment]
`{
  "server": [
    {
      "secure": false,
      "port": 80,
      "redirectToSecure": {
        "port": 443,
        "host": "devices.mydomain.com"
      }
    },
    {
      "secure": true,
      "port": 443,
      "options": {
        "certPath": "/home/user/ws-scrcpy/fullchain.pem",
        "keyPath": "/home/user/ws-scrcpy/privkey.pem"
      }
    }
  ]
}`

**Comment by MarkusPint** [comment]
Solved.

Needed to add `"runGoogTracker": true` to the config. I assumed if I don't specify it will be "true" by default.

**Comment by drauggres** [comment]
> I assumed if I don't specify it will be "true" by default, based on info from config.example.yaml.

Well, it should be. I will investigate, thank you for the report.
