### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [NetrisTV/ws-scrcpy#165]
Hey there!

I belong to an open source security research community, and a member (@whoamisky) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by drauggres** [comment]
Hi.

Thank you for the information. Please send me an email, you can find the address in any commit.

**Comment by JamieSlome** [comment]
@drauggres - thanks for your swift response! ⚡ 

I can arrange that for you, otherwise, you can view the private report directly here:

https://huntr.dev/bounties/dc7fc98f-4f4f-440a-b6f6-124a56ea36ef/
