### ISSUE TITLE
Possible to change folder structure to front-end and back-end

### ISSUE THREAD

**Issue by krishtoautomate** [NetrisTV/ws-scrcpy#169]
Possible to modify folder structure to front-end and back-end to allow other contributers to add interactive front-end like react or angular

**Comment by drauggres** [comment]
Hi there.
If you want to do it yourself, you are welcome.
If you are asking for me to do it, then sorry. I don't have time even to finish features that I want.

P.S. And I don't use react or angular, so I don't really know what to change and how.
