### ISSUE TITLE
Different network Issue

### ISSUE THREAD

**Issue by sheshnath1st** [NetrisTV/ws-scrcpy#17]
When I am trying the access device display and control on different network then it is not working.Can you please suggest it How can I resolve this issue

**Comment by drauggres** [comment]
Your mobile phone in this case is a server which listenins for connections on TCP port 8886.
You need to configure your network in order to connect (firewall, port frowarding, NAT, etc).
This is beyond this project.

**Comment by sree143342** [comment]
Can any one explain about what is the exact difference between Broadway, Native, h264BSD and tinyh264 decoders.

Advance thanks,

**Comment by drauggres** [comment]
In [v0.6.0](https://github.com/NetrisTV/ws-scrcpy/releases/tag/v0.6.0) you can select option `proxy over adb` in the interfaces list.
Server will automatically forward port from device and run proxy server when you select this option.
