### ISSUE TITLE
[Question][Research] Audio support : I need media Audio output from iPhone while mirroring screen using ws-scrcpy 

### ISSUE THREAD

**Issue by Raghavendra617** [NetrisTV/ws-scrcpy#177]
### Discussed in https://github.com/NetrisTV/ws-scrcpy/discussions/38

Can someone explain me how to get Media Audio output either from iPhone or MAC Book during mirroring the screen using ws-scrcpy

**Comment by drauggres** [comment]
Hi.

I've updated answer in #38 to cover iOS. Let's keep it one place.
