### ISSUE TITLE
How to get decoded frames

### ISSUE THREAD

**Issue by stoefln** [NetrisTV/ws-scrcpy#180]
Hi there, thanks for this great project!

I would need the frames decoded in full resolution. I saw that the [h264-converter](https://github.com/xevojapan/h264-converter) is used to decode the data, and forward it to the mediaSource which is assigned to the video tag.
I am not familiar with video decoding at all, so I don't get where I could get the decoded frames from. 
My guess was that it should be somewhere around [here](https://github.com/xevojapan/h264-converter/blob/master/src/index.ts#L152), right? 
Or is there any other place maybe inside of ws-scrcpy where I could access the decompressed frames?

**Comment by drauggres** [comment]
Hi.
h264-converter does not decode video, it creates mp4-container (google muxing) from raw h264-frames and feeds them to a mediaSource. After that, decoding and rendering is done internally by your browser, i.e. you can't access decoded frames (except capturing video-tag content). 

For decoded frames you need to look at other players/decodes:

https://github.com/NetrisTV/ws-scrcpy/blob/5af62721c450a50172af49c5f29b40898f844163/src/app/player/BroadwayPlayer.ts#L46-L48

https://github.com/NetrisTV/ws-scrcpy/blob/5af62721c450a50172af49c5f29b40898f844163/src/app/player/TinyH264Player.ts#L46-L50

https://github.com/NetrisTV/ws-scrcpy/blob/5af62721c450a50172af49c5f29b40898f844163/src/app/player/WebCodecsPlayer.ts#L89-L92

Also this could be usefull: [Difference between different decoders](https://github.com/NetrisTV/ws-scrcpy/discussions/30)

**Comment by drauggres** [comment]
For broadway.js and tinyh264 in the specified places a `Uint8Array` will contain a decoded frame in [YUV](https://en.wikipedia.org/wiki/YUV)-format. It is later trasnlated into RGB and is rendered on a canvas.

For WebCodecs `frame` is [VideoFrame](https://developer.mozilla.org/en-US/docs/Web/API/VideoFrame) (https://www.w3.org/TR/webcodecs/#videoframe-interface)

**Comment by stoefln** [comment]
@drauggres thanks a lot for the quick reply!
