### ISSUE TITLE
Would it be possible to create a minimal version of ws-scrcpy?

### ISSUE THREAD

**Issue by MilkFlavor** [NetrisTV/ws-scrcpy#185]
I really love this project so far. 
However, I have been trying to get rid of some features that aren't really required in my use case. Some of the things I'm looking to remove would be file listing, devtools, Xterm terminal, etc. This was pretty simple, however, would it be possible to get rid of the device list? For example, instead of going through the process of opening the browser, waiting for the device to be ready, and finally selecting a screen casting option to finally get to the mirror. The program just waits for the latest device to connect, then opening mirroring using something like electron (skipping the whole process of getting to the actual mirror). Could you think of any complications I might face with other components of ws-scrcpy?

**Comment by drauggres** [comment]
This sounds like original [scrcpy](https://github.com/Genymobile/scrcpy). Why don't you use it?

**Comment by MilkFlavor** [comment]
Mainly because I don't want to learn C, and because it's a lot more difficult/time-consuming. I think it'll be easier to just remove components than to learn a completely new language. For a bit of context, I'm trying to automate a game on my phone using OpenCV and (if I still feel like working on the project) maybe add Tenserflow's object detection component. I would do this with python, but it runs on 2 fps. So my next option would be to use C/C++, but I'm not willing to risk mental health cause of some compiler, and because I have experience with Javascript I found your project suitable to fork and changeup.

**Comment by drauggres** [comment]
Well, in this case I don't see any obstacles.

But be aware that broadway and tinyh264 are software decoders. And h264-converter does not really decode anything, it only creates fmp4 containers.

Feel free to fork or just copy the code you need.
Also you might want to look [here](https://github.com/NetrisTV/ws-scrcpy/discussions/182).

**Comment by MilkFlavor** [comment]
> But be aware that broadway and tinyh264 are software decoders. And h264-converter does not really decode anything, it only creates fmp4 containers.
 So I'm assuming Webcodecs would be the simplest way to obtain frames?

Also I remember something about the device list being crucial creating a connection of some sort. I unfortunately couldn't find which issue that was from. Should I be concerned about this?

**Comment by drauggres** [comment]
> So I'm assuming Webcodecs would be the simplest way to obtain frames?

I don't think it is possible to get raw bytes from VideoFrame from javascript. And WebCodecs is available only on chromium-based platforms (i.e. it should work in electron, but not in node.js).

> Also I remember something about the device list being crucial creating a connection of some sort.

I don't recall anything unusual. All you need is:
- get device list (same as `adb devices`)
- send `scrcpy-server.jar` to a device (`adb push`)
- start `scrcpy-server.jar` on a device (`adb shell CLASSPATH=... app_process ...`) 
- optional, forward server port if you configured it to listen only on localhost (`adb forward`)
- connect to the server with WebSocket and send "initial info" with settings.

**Comment by stoefln** [comment]
@MilkFlavor we are also trying to decode the video stream from scrcpy (for the same goal: automation based on computer vision). Let's stay in touch, I am sure we will find a way. ScrCpy offers a way to configure the encoder from the outside of the jar (no recompilation required), via params. 
https://github.com/Genymobile/scrcpy/blob/49434da36ea9bd52907609c08c0b644c2d0d6649/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L215
So my guess is: Either we can decode the h264 stream using opencv (opencv4nodejs library) or we can configure scrcpy to send jpeg data. If you want to have a chat about object detection via JS feel free to reach out!

**Comment by drauggres** [comment]
> ScrCpy offers a way to configure the encoder from the outside of the jar (no recompilation required), via params.

In this project I don't use original scrcpy-server. The [forked version](https://github.com/NetrisTV/scrcpy/tree/feature/websocket-v1.19.x) does not receive encoding parameters from the command line, but waits for them from the client via WebSocket. Also in this version you can change video settings on the fly.

> or we can configure scrcpy to send jpeg data.

scrcpy does not support streaming jpeg. I've seen a fork that adds jpeg support, but I think it is a regression.

**Comment by MilkFlavor** [comment]
> * get device list (same as `adb devices`)
> * send `scrcpy-server.jar` to a device (`adb push`)
> * start `scrcpy-server.jar` on a device (`adb shell CLASSPATH=... app_process ...`)
> * optional, forward server port if you configured it to listen only on localhost (`adb forward`)
> * connect to the server with WebSocket and send "initial info" with settings.

So like this?:
https://github.com/NetrisTV/ws-scrcpy/issues/20#issuecomment-627534399
`cd dist/public
adb push scrcpy-server.jar /data/local/tmp
adb shell
CLASSPATH=/data/local/tmp/scrcpy-server.jar nohup app_process / com.genymobile.scrcpy.Server 1.13 0 8000000 60 -1 false - false false 0 web 8886 > /dev/null&`

**Comment by stoefln** [comment]
I found that OpenCV has a VideoCapture class that can be used to decode a stream frame by frame:
https://stackoverflow.com/a/50706228/457059

@drauggres do you think it's possible to connect to the stream via OpenCV and the JS VideoPlayer in parallel? Or scrcpy doesn't accept multiple clients?

**Comment by drauggres** [comment]
> @drauggres do you think it's possible to connect to the stream via OpenCV and the JS VideoPlayer in parallel? Or scrcpy doesn't accept multiple clients?

The original scrcpy-server allows only one client (via unix socket).
The version in my [fork](https://github.com/NetrisTV/scrcpy/tree/feature/websocket-v1.19.x) works with multiple clients (via WebSocket).

**Comment by MilkFlavor** [comment]
So after a bit of reverse engineering, I'm around 50% done, but I need a bit of help on understanding how images are transferred into an h246. So far I have slimed down the project so all it consists of is a link to the players. However, it would be easier to just completely remove the device list and just show the iframe. Take a look at the screenshot below:
![Screenshot 2022-03-22 000439](https://user-images.githubusercontent.com/55917261/159533803-2fef6ff8-e44d-4aa8-95da-9b4002e881e9.png)

So is there a specific file that produces a frame and would it be possible to just cut and replace the device list file with the file that contains the iframe?

I was also wondering about ways to change the frames to cv:Mat format and I got two ideas : 

1. Wouldn't it be faster to just directly translate the frames inside scrcpy-server.jar then push the modified frames into the client to then match the template? 

2. I could also alter the image in the client right before it's servers it to the stream. However, I think this would give a lower fps.

Also, what is a "typings" and "types" folder?

If you think I made any mistakes please check out my fork: https://github.com/MilkFlavor/minimal-ws-scrcpy

**Comment by stoefln** [comment]
@drauggres, it's incredible how responsive you are, thanks so much!
Not sure how much "off topic" this is, but since @MilkFlavor and me basically want to achieve the same thing (decoding YUV stream to OpenCV RGB Mat), I post my StackOverflow question [here](https://stackoverflow.com/questions/71575073/decoding-h264-avc-with-opencv) (for reference). Hoping to get some answers soon.

@MilkFlavor Decoding on the client doesn't seem to be a good idea. Encoding is done to limit the bandwidth needed to transfer the stream. That's cool. Applying image processing / computer vision stuff on the client would be indeed an option, but it's going to slow down your mobile device. We try to avoid that because it might lead to skipped frames.

**Comment by MilkFlavor** [comment]
@stoefln Did you ever solve your problem? I had a similar problem, but I think that's a Broadway-specific problem.

**Comment by stoefln** [comment]
@MilkFlavor no, still didn't. Haven't given up, but haven't found enough time to get at it again.

**Comment by MilkFlavor** [comment]
I saw this project and thought it was kind of related to what you're trying to achieve. https://github.com/RobbertH/scrcpy-opencv

**Comment by MilkFlavor** [comment]
@stoefln If you're still interested in the project, I have somewhat completed what we're striving to achieve. The only downside, however, is that it's written in Python and C. Which isn't the worst thing possible considering that most machine learning libraries I'm looking to implement like Tensorflow and Pytorch were based around Python use. Here it is: [Androd-Mirror](https://github.com/MilkFlavor/Android-Mirror)

So far I have been able to receive images from the android device and display them using OpenCV. The core of the project is inspired from [this](https://pypi.org/project/scrcpy-client/). However, performance on my tiny Intel Celeron was laughable at best. I already faced this problem before so I used some of the tactics like profiling, threading and refactoring. Unfortunately, that gave me a 1-3 fps bump at max so I just decided to use Cython which compiles `.pyx` to C. This somehow gave me a 10-15 more fps letting me control my phone at 30-40fps while resizing and template matching using OpenCV.

I still need to add more documentation and fill out more files, but I'm pretty confident on the performance and versatility of the project.

**Comment by stoefln** [comment]
@MilkFlavor thanks so much for this update! It's great you managed. Since we are kind of trying to achieve the same goal: Would you be interested to connect somehow? Either a call or a chat? Would be great to hear from you!
reach me: [stephan.petzl at gemail dot com](https://github.com/stoefln)

**Comment by krishtoautomate** [comment]
can anyone tell me what is this message being sent to start stream:
<img width="506" alt="image" src="https://github.com/user-attachments/assets/cbbbaf4a-7534-4a51-af4a-1cdb6fdd15f4" />
