### ISSUE TITLE
error...

### ISSUE THREAD

**Issue by gamecln277** [NetrisTV/ws-scrcpy#19]
`dbug ADB Getting connected devices...
dbug ADB Connected devices: [{"udid":"77.77.77.9:5555","state":"device"}]
dbug ADB Running '/opt/androidSdk/platform-tools/adb -P 5037 -s 77.77.77.9\:5555 shell 'ip route|grep eth0|grep -v default''
dbug ADB Running '/opt/androidSdk/platform-tools/adb -P 5037 -s 77.77.77.9\:5555 shell getprop ro.product.model'
dbug ADB Current device property 'ro.product.model': SM-G970N
dbug ADB Running '/opt/androidSdk/platform-tools/adb -P 5037 -s 77.77.77.9\:5555 shell getprop ro.product.manufacturer'
dbug ADB Current device property 'ro.product.manufacturer': samsung
dbug ADB Running '/opt/androidSdk/platform-tools/adb -P 5037 -s 77.77.77.9\:5555 shell 'for a in `find /proc -type d -maxdepth 1 -user shell -group shell 2>/dev/null`; do test -f "$a/cmdline" && grep -av find "$a/cmdline" |grep -sa scrcpy 2>&1 > /dev/null && echo $a |cut -d "/" -f 3; done; exit 0''
info ServerDeviceConnection [77.77.77.9:5555] PIDs: []
dbug ADB Running '/opt/androidSdk/platform-tools/adb -P 5037 -s 77.77.77.9\:5555 shell mkdir -p /data/local'
dbug ADB Running '/opt/androidSdk/platform-tools/adb -P 5037 -s 77.77.77.9\:5555 push /root/ws-scrcpy/dist/public/scrcpy-server.jar /data/local/tmp/'
dbug ADB Running '/opt/androidSdk/platform-tools/adb -P 5037 -s 77.77.77.9\:5555 shell 'CLASSPATH=/data/local/tmp/scrcpy-server.jar nohup app_process / com.genymobile.scrcpy.Server 0 8000000 false - false true web >/dev/null&''
ERR! ServerDeviceConnection Error: Command '/opt/androidSdk/platform-tools/adb -P 5037 -s 77.77.77.9\:5555 shell 'CLASSPATH=/data/local/tmp/scrcpy-server.jar nohup app_process / com.genymobile.scrcpy.Server 0 8000000 false - false true web >/dev/null&'' timed out after 20000ms
ERR! ServerDeviceConnection     at Timeout.setTimeout (/root/ws-scrcpy/node_modules/teen_process/lib/exec.js:125:19)
ERR! ServerDeviceConnection     at ontimeout (timers.js:436:11)
ERR! ServerDeviceConnection     at tryOnTimeout (timers.js:300:5)
ERR! ServerDeviceConnection     at listOnTimeout (timers.js:263:5)
ERR! ServerDeviceConnection     at Timer.processTimers (timers.js:223:10)
`

I don't know why...
looks like 
`dbug ADB Running '/opt/androidSdk/platform-tools/adb -P 5037 -s 77.77.77.9\:5555 shell 'CLASSPATH=/data/local/tmp/scrcpy-server.jar nohup app_process / com.genymobile.scrcpy.Server 0 8000000 false - false true web >/dev/null&''`
this is error

**Comment by gamecln277** [comment]
I find some log
`[root@ws-scrcpy ws-scrcpy1.13]# adb -P 5037 -s 77.77.77.9\:5555 shell 'CLASSPATH=/data/local/tmp/scrcpy-server.jar nohup app_process / com.genymobile.scrcpy.Server 0 8000000 false - false true web'
[server] ERROR: WebSocket error
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:454)
        at sun.nio.ch.Net.bind(Net.java:446)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
        at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:505)
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:315)
        at com.genymobile.scrcpy.WebSocketConnection.<init>(WebSocketConnection.java:20)
        at com.genymobile.scrcpy.Server.main(Server.java:116)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:290)
`

**Comment by drauggres** [comment]
1. You are using old version, always try latest before openning issues
2. This is normal. It says: "`Command [..] timed out after 20000ms`" because it was waiting for command exit code, but server is actually will never stop (until it's killed or device is rebooted).

**Comment by drauggres** [comment]
>`ERROR: WebSocket error java.net.BindException: Address already in use`

In this case something else is listening on tcp:8886. Currently this problem is not handled, but you can change the port [here](https://github.com/NetrisTV/ws-scrcpy/blob/master/src/server/Constants.ts#L2).

**Comment by gamecln277** [comment]
I fix that just input
`/opt/androidSdk/platform-tools/adb -P 5038 -s 77.77.77.9\:5555 shell 'CLASSPATH=/data/local/tmp/scrcpy-server.jar nohup app_process / com.genymobile.scrcpy.Server 0 8000000 false - false true web >/dev/null&'`

I change 5037 to 5038...
how can I fix it forever?
Is it a bug?

**Comment by gamecln277** [comment]
I really sure I use the latest version...

**Comment by drauggres** [comment]
> I really sure I use the latest version...

I'm sorry, but you don't. Try to download zip-achive from [releases page](https://github.com/NetrisTV/ws-scrcpy/releases) if you are not familar with `git`.

**Comment by gamecln277** [comment]
sorry bor...I go into old folder....
do you have any message software? fb or telegram line
I think it's ㄩuch more convenient

**Comment by drauggres** [comment]
gihub is fine

**Comment by gamecln277** [comment]
ok~ thanks bro~
