### ISSUE TITLE
Can scrcpy support webosckt's code repository?

### ISSUE THREAD

**Issue by zhangpeibisha** [NetrisTV/ws-scrcpy#197]
I hope I can make special modifications in the repository, thank you

**Comment by drauggres** [comment]
Sorry, I don't quite understand what you mean.

**Comment by zhangpeibisha** [comment]
I can't find a scrcpy service that supports websockt in the https://github.com/Genymobile/scrcpy repository, but there is a packaged scrcpy file that supports websocket in your repository. I would like to know if you wrote scrcpy that supports websocket github repository address, so that I can write some other functions based on yours.

**Comment by drauggres** [comment]
https://github.com/NetrisTV/ws-scrcpy/blob/master/README.md#scrcpy-websocket-fork

**Comment by zhangpeibisha** [comment]
Thanks
