### ISSUE TITLE
LDPlayer4

### ISSUE THREAD

**Issue by gamecln277** [NetrisTV/ws-scrcpy#20]
`> ws-scrcpy@0.2.0 start /root/ws-scrcpy1.13/dist
> cd server && node index.js

[77.77.77.9:5555] Result: 
[77.77.77.9:5555] Result: 
[77.77.77.9:5555] Result: 
[77.77.77.9:5555] Result: 
[77.77.77.9:5555] Result: 
[77.77.77.9:5555] error: failed to start server
[77.77.77.9:5555] Result: 
[77.77.77.9:5555] Result: 
[77.77.77.9:5555] Result: 
[77.77.77.9:5555] Result: 
[77.77.77.9:5555] Result: 
[77.77.77.9:5555] error: failed to start server
(node:6819) UnhandledPromiseRejectionWarning: TypeError: First argument must be a valid error code number
    at Sender.close (/root/ws-scrcpy1.13/node_modules/ws/lib/sender.js:108:13)
    at WebSocket.close (/root/ws-scrcpy1.13/node_modules/ws/lib/websocket.js:229:18)
    at WebSocketServer.wss.on (/root/ws-scrcpy1.13/dist/server/index.js:82:16)
    at WebSocketServer.emit (events.js:198:13)
    at handleUpgrade (/root/ws-scrcpy1.13/node_modules/ws/lib/websocket-server.js:90:18)
    at WebSocketServer.completeUpgrade (/root/ws-scrcpy1.13/node_modules/ws/lib/websocket-server.js:329:5)
    at WebSocketServer.handleUpgrade (/root/ws-scrcpy1.13/node_modules/ws/lib/websocket-server.js:245:10)
    at Server.upgrade (/root/ws-scrcpy1.13/node_modules/ws/lib/websocket-server.js:89:16)
    at Server.emit (events.js:198:13)
    at onParserExecuteCommon (_http_server.js:567:14)
    at onParserExecute (_http_server.js:513:3)
(node:6819) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6819) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[77.77.77.9:5555] Result: 
[77.77.77.9:5555] Result: 
[77.77.77.9:5555] Result: 
[77.77.77.9:5555] Result: 
[77.77.77.9:5555] error: failed to start server
`

I go to http://77.77.77.31:8000/ it have show a list
but in stream didn't show anything...
http://77.77.77.31:8000/#!showFps=true&action=stream&udid=77.77.77.9%3A5555&decoder=broadway&ip=&port=8887
http://77.77.77.31:8000/#!showFps=true&action=stream&udid=77.77.77.9%3A5555&decoder=native&ip=&port=8887
http://77.77.77.31:8000/#!showFps=true&action=stream&udid=77.77.77.9%3A5555&decoder=h264bsd&ip=&port=8887
all show white page

**Comment by gamecln277** [comment]
Is about node version?
I use v10.19.0

**Comment by gamecln277** [comment]
I reinstall to nodejs 12 but still the same

**Comment by drauggres** [comment]
Node version does not matter in this case. Sometimes app fails to start server.
Look at the `PID` column if it has `-1` then server is not running. Try to refresh page, this will trigger check-install sequence again.

If it does not help, you can try to start server manually:
```shell
cd dist/public
adb push scrcpy-server.jar /data/local/tmp
adb shell
CLASSPATH=/data/local/tmp/scrcpy-server.jar nohup app_process / com.genymobile.scrcpy.Server 1.13 0 8000000 60 -1 false - false false 0 web 8886&
``` 

P.S. this is not related to the problem, but you shouldn't run applications as `root`

**Comment by gamecln277** [comment]
`[root@ws-scrcpy ws-scrcpy1.13]# cd dist/public
[root@ws-scrcpy public]# adb push scrcpy-server.jar /data/local/tmp
scrcpy-server.jar: 1 file pushed, 0 skipped. 986.5 MB/s (129480 bytes in 0.000s)
[root@ws-scrcpy public]# adb shell
aosp:/ # CLASSPATH=/data/local/tmp/scrcpy-server.jar nohup app_process / com.genymobile.scrcpy.Server 1.13 0 8000000 60 -1 false - false false 0 web 8886&
[1] 29520
aosp:/ # nohup: //nohup.out: Read-only file system
`

**Comment by drauggres** [comment]
Sorry:
`CLASSPATH=/data/local/tmp/scrcpy-server.jar nohup app_process / com.genymobile.scrcpy.Server 1.13 0 8000000 60 -1 false - false false 0 web 8886 > /dev/null&`

**Comment by gamecln277** [comment]
`aosp:/ # java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:454)
        at sun.nio.ch.Net.bind(Net.java:446)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
        at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:505)
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:315)
        at com.genymobile.scrcpy.WebSocketConnection.<init>(WebSocketConnection.java:20)
        at com.genymobile.scrcpy.Server.main(Server.java:142)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:290)
`

**Comment by drauggres** [comment]
Last parameter (8886) is port number, you can change it.

**Comment by gamecln277** [comment]
I change to 8877 but still the same show
`[root@ws-scrcpy public]# adb shell
 nohup app_process / com.genymobile.scrcpy.Server 1.13 0 8000000 60 -1 false - false false 0 web 8886 > /dev/null&                                              <
[1] 4080
`


and I try shell
`[root@ws-scrcpy public]# adb shell
 nohup app_process / com.genymobile.scrcpy.Server 1.13 0 8000000 60 -1 false - false false 0 web 8886 > /dev/null&                                              <
[1] 4080
`
It works fine...

**Comment by gamecln277** [comment]
am other thing.....
how to exit that shell mode....
I try exit quit bye but no effect

**Comment by drauggres** [comment]
> `UnhandledPromiseRejectionWarning: TypeError: First argument must be a valid error code number`

This is not related to server on the device (default port 8886), it is about WebSocket server on your computer (port 8000) and should be fixed in the `master` branch now.

>how to exit that shell mode....
`exit` or pressing Ctrl+d should work

**Comment by gamecln277** [comment]
> ws-scrcpy@0.2.0 start /root/ws-scrcpy1.13/dist
> cd server && node index.js

(node:2254) UnhandledPromiseRejectionWarning: TypeError: First argument must be a valid error code number
    at Sender.close (/root/ws-scrcpy1.13/node_modules/ws/lib/sender.js:108:13)
    at WebSocket.close (/root/ws-scrcpy1.13/node_modules/ws/lib/websocket.js:229:18)
    at WebSocketServer.<anonymous> (/root/ws-scrcpy1.13/dist/server/index.js:72:12)
    at WebSocketServer.emit (events.js:310:20)
    at /root/ws-scrcpy1.13/node_modules/ws/lib/websocket-server.js:90:18
    at WebSocketServer.completeUpgrade (/root/ws-scrcpy1.13/node_modules/ws/lib/websocket-server.js:329:5)
    at WebSocketServer.handleUpgrade (/root/ws-scrcpy1.13/node_modules/ws/lib/websocket-server.js:245:10)
    at Server.upgrade (/root/ws-scrcpy1.13/node_modules/ws/lib/websocket-server.js:89:16)
    at Server.emit (events.js:310:20)
    at onParserExecuteCommon (_http_server.js:642:14)
    at onParserExecute (_http_server.js:583:3)
(node:2254) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2254) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> I use git pull and Already up to date.

**Comment by gamecln277** [comment]
adb logcat
I think you want this ~
[(https://pastebin.com/Akwh17za)]

**Comment by drauggres** [comment]
> I use git pull and Already up to date.

Yep, my mistake (codes [should be](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent) between 4000 and 4999, who knew?). Please try again.

BTW, Have you tried original [scrcpy](https://github.com/Genymobile/scrcpy), does it work?

**Comment by gamecln277** [comment]
> First argument must be a valid error code number

Yes,this problem is fix~

the last problem 
https://pastebin.com/GXYNhQPE

> BTW, Have you tried original scrcpy, does it work?
I haven't try...
maybe I should try it?

**Comment by drauggres** [comment]
Look's like scrcpy-server on devices started, but "checker" ([these](https://github.com/NetrisTV/ws-scrcpy/blob/master/src/server/ServerDeviceConnection.ts#L15-L17) ugly lines of code) can not find it's `pid`. At least you should be able to open a stream.

Are you using rooted device (or emulator with root)? What is the output of `adb shell id`?

**Comment by gamecln277** [comment]
Yes I use rooted emulator  device

**Comment by drauggres** [comment]
Don't. Just reboot the emulator (`adb reboot`).
You can keep `npm start` running, it will find "new" devices/emulators and run server on them automatically.

**Comment by gamecln277** [comment]
> adb shell id
`uid=0(root) gid=0(root) groups=0(root),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats`

**Comment by drauggres** [comment]
> adb shell id
> `uid=0(root) gid=0(root) groups=0(root),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats`

Yep, this means that server also will run as `root` and "checker" will not find it, because it searches only for processes of `shell` user.

**Comment by gamecln277** [comment]
Nooooooo~
how can I do...
If i turn off root,I can not connect the adb..

**Comment by drauggres** [comment]
Why? It work fine without root.

**Comment by gamecln277** [comment]
IDK..
It always say 
List of devices attached
77.77.77.10:5555        offline

**Comment by drauggres** [comment]
What operating system are you on?

**Comment by gamecln277** [comment]
77.77.77.2 I use win10 
77.77.77.31 VM CentOS 8 with ws-scrcpy
77.77.77.10  emulator

**Comment by drauggres** [comment]
Why so complicated? You can run ws-scrcpy on windows.
Anyway, try to run this from root console on CentOS:
- `adb kill-server`
- `killall adb` (just to be sure)
Then as user (not root):
- `adb start-server`
- `adb connect 77.77.77.10:5555`

**Comment by drauggres** [comment]
Or you can change `-user shell -group shell` to `-user root -group root` [here](https://github.com/NetrisTV/ws-scrcpy/blob/master/src/server/ServerDeviceConnection.ts#L15) if you want to stay as root (but I advise you against).

**Comment by gamecln277** [comment]
wait....
I use my win10 can connect to  emulator 
but my CentOS can't...
WHY??

**Comment by drauggres** [comment]
No idea. Sorry, this is beyond the area, where I willing to go.

**Comment by gamecln277** [comment]
I try to use internet to connect adb and it work!
but web still the same....
PID = -1
stream white page
[pastebin](https://pastebin.com/1KECQnYJ)

**Comment by gamecln277** [comment]
> uid=0(root) gid=0(root) groups=0(root),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats

Why my uid gid still root
I very sure I turn off root

**Comment by gamecln277** [comment]
05-13 06:20:00.001  1432  1432 I ActivityManager: Killing 2310:com.google.process.gapps/u0a43 (adj 906): empty #17
05-13 06:20:00.013  1432  3264 D ActivityManager: cleanUpApplicationRecord -- 2310
05-13 06:20:09.575 10203 10203 W System.err: java.lang.Exception: show AlertDialog! title=
05-13 06:20:09.575 10203 10203 W System.err:    at android.app.AlertDialog.show(AlertDialog.java:134)
05-13 06:20:09.575 10203 10203 W System.err:    at com.android.internal.view.menu.MenuDialogHelper.show(MenuDialogHelper.java:86)
05-13 06:20:09.575 10203 10203 W System.err:    at com.android.internal.view.menu.ContextMenuBuilder.showDialog(ContextMenuBuilder.java:88)
05-13 06:20:09.575 10203 10203 W System.err:    at com.android.internal.policy.DecorView.showContextMenuForChildInternal(DecorView.java:793)
05-13 06:20:09.575 10203 10203 W System.err:    at com.android.internal.policy.DecorView.showContextMenuForChild(DecorView.java:763)
05-13 06:20:09.575 10203 10203 W System.err:    at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:773)
05-13 06:20:09.575 10203 10203 W System.err:    at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:773)
05-13 06:20:09.575 10203 10203 W System.err:    at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:773)
05-13 06:20:09.575 10203 10203 W System.err:    at android.view.View.showContextMenu(View.java:5784)
05-13 06:20:09.575 10203 10203 W System.err:    at jackpal.androidterm.emulatorview.EmulatorView.onLongPress(EmulatorView.java:1135)
05-13 06:20:09.575 10203 10203 W System.err:    at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:770)
05-13 06:20:09.575 10203 10203 W System.err:    at android.view.GestureDetector.-wrap0(GestureDetector.java)
05-13 06:20:09.575 10203 10203 W System.err:    at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293)
05-13 06:20:09.575 10203 10203 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
05-13 06:20:09.575 10203 10203 W System.err:    at android.os.Looper.loop(Looper.java:154)
05-13 06:20:09.575 10203 10203 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6121)
05-13 06:20:09.575 10203 10203 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
05-13 06:20:09.575 10203 10203 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
05-13 06:20:09.575 10203 10203 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
05-13 06:20:09.613 10203 10220 E EGL_adreno: tid 10220: eglSurfaceAttrib(1323): error 0x3009 (EGL_BAD_MATCH)
05-13 06:20:09.613 10203 10220 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x977feec0, error=EGL_BAD_MATCH
05-13 06:20:09.613 10203 10220 D EGL_adreno: eglMakeCurrent: 0xacb04060: ver 3 1 (tinfo 0xacb03250)
05-13 06:20:09.635 10203 10220 D EGL_adreno: eglMakeCurrent: 0xacb04060: ver 3 1 (tinfo 0xacb03250)
05-13 06:20:09.636 10203 10220 D EGL_adreno: eglMakeCurrent: 0xacb04060: ver 3 1 (tinfo 0xacb03250)
05-13 06:20:10.419  1286  1465 D audio_hw_hal: raw_start_output_stream, stream=0xb6e43140, sampleRate=44100, channel=2, bps=16, bufSize=2880
05-13 06:20:10.419  1286  1465 W audio_hw_hal: out_write bytes length 0

**Comment by gamecln277** [comment]
I use genymotion and all work on....
I really want to fix this question on my LDPlayer emulator

**Comment by gamecln277** [comment]
I have found I use genymotion and input adb shell id
`
uid=0(root) gid=0(root) groups=0(root),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc)
`
it show uid gid group is root too,but I can use stream,so I think problem is not here

**Comment by drauggres** [comment]
Problem is here:
> Look's like scrcpy-server on devices started, but "checker" ([these](https://github.com/NetrisTV/ws-scrcpy/blob/master/src/server/ServerDeviceConnection.ts#L15-L17) ugly lines of code) can not find it's `pid`. At least you should be able to open a stream.

> Yep, this means that server also will run as `root` and "checker" will not find it, because it searches only for processes of `shell` user.

I tried to install LDPlayer, but it doesn't work for me, but I noticed option that enables `ROOT` in settings. You can either disable it or:

> Or you can change `-user shell -group shell` to `-user root -group root` [here](https://github.com/NetrisTV/ws-scrcpy/blob/master/src/server/ServerDeviceConnection.ts#L15) if you want to stay as root (but I advise you against).

**Comment by gamecln277** [comment]
> change -user shell -group shell to -user root -group root

I try that but it will got anyother error in adb logcat
`java.net.BindException: Address already in use`

I try ganymotion with root ,It works very perfectly!
and genymotion's adb shell id show
`uid=0(root) gid=0(root) groups=0(root),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc)`
so I think problem is not about -user shell -group shell.
It's about ws-scrcpy can't get some LDPlayer4 information.
but when I use scrcpy , it works  perfectly with LDPlayer4 ....

**Comment by gamecln277** [comment]
may I help you to test something?
I very like this repo~

**Comment by drauggres** [comment]
Problem with `Address already in use` is fixable, we need to figure out how to find scrcpy process PID.
This problem does not affect any functions related to streaming and input events.

Sorry, I don't have time right now to work on this.

P.S. you can set `DEBUG` environment variable to '*' to see all communications with `adb`:
> export DEBUG='*'; npm start

P.P.S. Also you should try [port forwarding](https://github.com/NetrisTV/ws-scrcpy#known-issues), (you will need to change `ip` parameter in the streaming url after that)

**Comment by gamecln277** [comment]
adb:command Send '001Ehost:transport:77.77.77.9:5555' +573ms
  adb:command Send '00B0shell:CLASSPATH=/data/local/tmp/scrcpy-server.jar nohup app_process / com.genymobile.scrcpy.Server 1.13 0 8000000 60 -1 false - false false 0 web 8877 > /data/local/tmp/OUTPUT&' +0ms
[77.77.77.9:5555] Result: 
  adb:command Send '001Ehost:transport:77.77.77.9:5555' +336ms
  adb:command Send '0044shell:while getprop sys.boot_completed 2>/dev/null; do sleep 1; done' +0ms
  adb:command Send '001Ehost:transport:77.77.77.9:5555' +44ms
  adb:command Send '00F6shell:for a in `find /proc -type d -maxdepth 1 -user root -group root 2>/dev/null`; do test -f "$a/cmdline" && grep -av find "$a/cmdline" |grep -sa com.genymobile.scrcpy.Server |grep 1.13 2>&1 > /dev/null && echo $a |cut -d "/" -f 3; done; exit 0' +0ms
  adb:command Send '001Ehost:transport:77.77.77.9:5555' +583ms
  adb:command Send '00B0shell:CLASSPATH=/data/local/tmp/scrcpy-server.jar nohup app_process / com.genymobile.scrcpy.Server 1.13 0 8000000 60 -1 false - false false 0 web 8877 > /data/local/tmp/OUTPUT&' +0ms
[77.77.77.9:5555] Result: 
  adb:command Send '001Ehost:transport:77.77.77.9:5555' +394ms
  adb:command Send '0044shell:while getprop sys.boot_completed 2>/dev/null; do sleep 1; done' +0ms
  adb:command Send '001Ehost:transport:77.77.77.9:5555' +44ms
  adb:command Send '00F6shell:for a in `find /proc -type d -maxdepth 1 -user root -group root 2>/dev/null`; do test -f "$a/cmdline" && grep -av find "$a/cmdline" |grep -sa com.genymobile.scrcpy.Server |grep 1.13 2>&1 > /dev/null && echo $a |cut -d "/" -f 3; done; exit 0' +0ms
  adb:command Send '001Ehost:transport:77.77.77.9:5555' +606ms
  adb:command Send '00B0shell:CLASSPATH=/data/local/tmp/scrcpy-server.jar nohup app_process / com.genymobile.scrcpy.Server 1.13 0 8000000 60 -1 false - false false 0 web 8877 > /data/local/tmp/OUTPUT&' +1ms
[77.77.77.9:5555] Result: 
  adb:command Send '001Ehost:transport:77.77.77.9:5555' +325ms
  adb:command Send '0044shell:while getprop sys.boot_completed 2>/dev/null; do sleep 1; done' +0ms
  adb:command Send '001Ehost:transport:77.77.77.9:5555' +44ms
  adb:command Send '00F6shell:for a in `find /proc -type d -maxdepth 1 -user root -group root 2>/dev/null`; do test -f "$a/cmdline" && grep -av find "$a/cmdline" |grep -sa com.genymobile.scrcpy.Server |grep 1.13 2>&1 > /dev/null && echo $a |cut -d "/" -f 3; done; exit 0' +0ms
[77.77.77.9:5555] error: failed to start server

**Comment by gamecln277** [comment]
> in adb logcat it loop about this
05-15 01:38:44.525  3356  5654 V GcmHandler: Get Id: 
05-15 01:38:44.525  3356  5654 V GcmHandler: Get Version: -1 || Current: 2350
05-15 01:38:44.525  3356  5654 V GcmHandler: Firebase Instance Id Start
05-15 01:38:44.525  3356  5654 V GcmHandler: Firebase Instance Id End
05-15 01:38:44.526  3356  6730 E CrossProcessLock: encountered error while creating and acquiring the lock, ignoring
05-15 01:38:44.526  3356  6730 E CrossProcessLock: java.io.FileNotFoundException: /data/user/0/com.madhead.tos.zh.ex/files/generatefid.lock: open failed: EACCES (05-15 01:38:44.526  3356  6730 E CrossProcessLock:      at libcore.io.IoBridge.open(IoBridge.java:455)
05-15 01:38:44.526  3356  6730 E CrossProcessLock:      at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247)
05-15 01:38:44.526  3356  6730 E CrossProcessLock:      at com.google.firebase.installations.CrossProcessLock.acquire(com.google.firebase:firebase-installations@@05-15 01:38:44.526  3356  6730 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations.getPrefsWithGeneratedIdMultiProcessSafe(com.goo05-15 01:38:44.526  3356  6730 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations.doRegistrationInternal(com.google.firebase:fire05-15 01:38:44.526  3356  6730 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations.doGetId(com.google.firebase:firebase-installati05-15 01:38:44.526  3356  6730 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations.access$lambda$0(com.google.firebase:firebase-in05-15 01:38:44.526  3356  6730 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations$$Lambda$1.run(com.google.firebase:firebase-inst05-15 01:38:44.526  3356  6730 E CrossProcessLock:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-15 01:38:44.526  3356  6730 E CrossProcessLock:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-15 01:38:44.526  3356  6730 E CrossProcessLock:      at java.lang.Thread.run(Thread.java:761)
05-15 01:38:44.526  3356  6730 E CrossProcessLock: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
05-15 01:38:44.526  3356  6730 E CrossProcessLock:      at libcore.io.Posix.open(Native Method)
05-15 01:38:44.526  3356  6730 E CrossProcessLock:      at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
05-15 01:38:44.526  3356  6730 E CrossProcessLock:      at libcore.io.IoBridge.open(IoBridge.java:441)
05-15 01:38:44.526  3356  6730 E CrossProcessLock:      ... 10 more
05-15 01:38:44.527  3356  5661 E CrossProcessLock: encountered error while creating and acquiring the lock, ignoring
05-15 01:38:44.527  3356  5661 E CrossProcessLock: java.io.FileNotFoundException: /data/user/0/com.madhead.tos.zh.ex/files/generatefid.lock: open failed: EACCES (05-15 01:38:44.527  3356  5661 E CrossProcessLock:      at libcore.io.IoBridge.open(IoBridge.java:455)
05-15 01:38:44.527  3356  5661 E CrossProcessLock:      at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247)
05-15 01:38:44.527  3356  5661 E CrossProcessLock:      at com.google.firebase.installations.CrossProcessLock.acquire(com.google.firebase:firebase-installations@@05-15 01:38:44.527  3356  5661 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations.getPrefsWithGeneratedIdMultiProcessSafe(com.goo05-15 01:38:44.527  3356  5661 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations.doNetworkCall(com.google.firebase:firebase-inst05-15 01:38:44.527  3356  5661 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationInternal$0(com.google.fire05-15 01:38:44.527  3356  5661 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations$$Lambda$5.run(com.google.firebase:firebase-inst05-15 01:38:44.527  3356  5661 E CrossProcessLock:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-15 01:38:44.527  3356  5661 E CrossProcessLock:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-15 01:38:44.527  3356  5661 E CrossProcessLock:      at java.lang.Thread.run(Thread.java:761)
05-15 01:38:44.527  3356  5661 E CrossProcessLock: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
05-15 01:38:44.527  3356  5661 E CrossProcessLock:      at libcore.io.Posix.open(Native Method)
05-15 01:38:44.527  3356  5661 E CrossProcessLock:      at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
05-15 01:38:44.527  3356  5661 E CrossProcessLock:      at libcore.io.IoBridge.open(IoBridge.java:441)
05-15 01:38:44.527  3356  5661 E CrossProcessLock:      ... 9 more
05-15 01:38:44.527  3356  6730 E CrossProcessLock: encountered error while creating and acquiring the lock, ignoring
05-15 01:38:44.527  3356  6730 E CrossProcessLock: java.io.FileNotFoundException: /data/user/0/com.madhead.tos.zh.ex/files/generatefid.lock: open failed: EACCES (05-15 01:38:44.527  3356  6730 E CrossProcessLock:      at libcore.io.IoBridge.open(IoBridge.java:455)
05-15 01:38:44.527  3356  6730 E CrossProcessLock:      at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247)
05-15 01:38:44.527  3356  6730 E CrossProcessLock:      at com.google.firebase.installations.CrossProcessLock.acquire(com.google.firebase:firebase-installations@@05-15 01:38:44.527  3356  6730 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations.getPrefsWithGeneratedIdMultiProcessSafe(com.goo05-15 01:38:44.527  3356  6730 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations.doRegistrationInternal(com.google.firebase:fire05-15 01:38:44.527  3356  6730 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations.doGetAuthTokenWithoutForceRefresh(com.google.fi05-15 01:38:44.527  3356  6730 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations.access$lambda$2(com.google.firebase:firebase-in05-15 01:38:44.527  3356  6730 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations$$Lambda$3.run(com.google.firebase:firebase-inst05-15 01:38:44.527  3356  6730 E CrossProcessLock:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-15 01:38:44.527  3356  6730 E CrossProcessLock:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-15 01:38:44.527  3356  6730 E CrossProcessLock:      at java.lang.Thread.run(Thread.java:761)
05-15 01:38:44.527  3356  6730 E CrossProcessLock: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
05-15 01:38:44.527  3356  6730 E CrossProcessLock:      at libcore.io.Posix.open(Native Method)
05-15 01:38:44.527  3356  6730 E CrossProcessLock:      at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
05-15 01:38:44.527  3356  6730 E CrossProcessLock:      at libcore.io.IoBridge.open(IoBridge.java:441)
05-15 01:38:44.527  3356  6730 E CrossProcessLock:      ... 10 more
05-15 01:38:45.307  3356  5661 E CrossProcessLock: encountered error while creating and acquiring the lock, ignoring
05-15 01:38:45.307  3356  5661 E CrossProcessLock: java.io.FileNotFoundException: /data/user/0/com.madhead.tos.zh.ex/files/generatefid.lock: open failed: EACCES (05-15 01:38:45.307  3356  5661 E CrossProcessLock:      at libcore.io.IoBridge.open(IoBridge.java:455)
05-15 01:38:45.307  3356  5661 E CrossProcessLock:      at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247)
05-15 01:38:45.307  3356  5661 E CrossProcessLock:      at com.google.firebase.installations.CrossProcessLock.acquire(com.google.firebase:firebase-installations@@05-15 01:38:45.307  3356  5661 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations.getPrefsWithGeneratedIdMultiProcessSafe(com.goo05-15 01:38:45.307  3356  5661 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations.doNetworkCall(com.google.firebase:firebase-inst05-15 01:38:45.307  3356  5661 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationInternal$0(com.google.fire05-15 01:38:45.307  3356  5661 E CrossProcessLock:      at com.google.firebase.installations.FirebaseInstallations$$Lambda$5.run(com.google.firebase:firebase-inst05-15 01:38:45.307  3356  5661 E CrossProcessLock:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-15 01:38:45.307  3356  5661 E CrossProcessLock:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-15 01:38:45.307  3356  5661 E CrossProcessLock:      at java.lang.Thread.run(Thread.java:761)
05-15 01:38:45.307  3356  5661 E CrossProcessLock: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
05-15 01:38:45.307  3356  5661 E CrossProcessLock:      at libcore.io.Posix.open(Native Method)
05-15 01:38:45.307  3356  5661 E CrossProcessLock:      at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
05-15 01:38:45.307  3356  5661 E CrossProcessLock:      at libcore.io.IoBridge.open(IoBridge.java:441)
05-15 01:38:45.307  3356  5661 E CrossProcessLock:      ... 9 more
05-15 01:38:45.333  3356  3382 E FirebaseInstanceId: Topic sync or token retrieval failed on hard failure exceptions: FIS_AUTH_ERROR. Won't retry the operation.

**Comment by drauggres** [comment]
> in adb logcat it loop about this
This log is not related (something else producing it).

I am almost sure that port is not available outside of VM. You'll need to forward it.

**Comment by gamecln277** [comment]
so  weird....
I have turned off all firewall and SElinux.
Do you mean my browser can't connect to my VM,or VM to emu?

**Comment by drauggres** [comment]
> Do you mean my browser can't connect to my VM,or VM to emu?

Browser to emu (I'm talking about "empty streaming page" problem, not about `PID: -1`)

**Comment by gamecln277** [comment]
okey!
I find in this address, "&ip"= is space
`http://77.77.77.31:8000/#!showFps=true&action=stream&udid=77.77.77.9%3A5555&decoder=broadway&ip=&port=8877`

**Comment by gamecln277** [comment]
ohhh
I input ip and F5
It work!!

but.. h264 screen is blask

**Comment by drauggres** [comment]
> I find in this address, "&ip"= is space

Year, it's trying to find ip address of the wireless interface, but your emulator only have "wired", I guess.

>but.. h264 screen is black
Try other decoders (h264bsd or native).
Also look in the `Developer Tools` for WebSocket connection. You should see outcoming messages than you clicking on the screen and incoming with h264 frames then it's updated.

**Comment by gamecln277** [comment]
My emulator default use wifi



I use Developer Tools for WebSocket connection in messages I see a lot of garbled run
and I touch screen drag screen,screen still black

**Comment by drauggres** [comment]
I'm going to close this.

Please try the latest version:
- you can select `proxy over adb` in the list of network interfaces (no need forward port manually anymore)
- you can try to select different encoder (if there are any)

If this is still actual and latest version also doesn't work, feel free to reopen (or create new issue).
