### ISSUE TITLE
where should i put the configuration file to?

### ISSUE THREAD

**Issue by taogogo** [NetrisTV/ws-scrcpy#209]
I'm trying to change from HTTP to HTTPS, but when should i put the configuration file to?
I tried to put it in the ws-scrcpy code path and run a command "WS_SCRCPY_CONFIG="/Users/tgg/config.yaml", then run command "npm start".
But nothing happened, could you give me some suggestions to solve this problem?

**Comment by drauggres** [comment]
Hi.
You should do it like this (one command):
```shell
WS_SCRCPY_CONFIG=/Users/tgg/config.yaml npm start
```
or like this (two commands):
```shell
export WS_SCRCPY_CONFIG=/Users/tgg/config.yaml
npm start
```

https://stackoverflow.com/questions/1158091/defining-a-variable-with-or-without-export
