### ISSUE TITLE
Mobile browser as a client

### ISSUE THREAD

**Issue by gamecln277** [NetrisTV/ws-scrcpy#21]
have any possible to let phone use?
I use it to drag phone ,web page will move....

**Comment by drauggres** [comment]
You should be able to just click on the image to generate input events.
Have you tried original scrcpy, does it work?

**Comment by gamecln277** [comment]
Yes , it work fine
But I need to use phone to control many emu.
so I very hope this software can work in my requirement...please

**Comment by drauggres** [comment]
So, you are using browser on a smartphone to open ws-scrcpy web page, is that correct?
I never tried to open it on a phone. I'm not sure that it's possible to use scroll/drag in ws-scrcpy on a common browser on a phone.

**Comment by gamecln277** [comment]
YES!thst is I mean!
If web screen can fullscreen,maybe It will work fine?
I guess

**Comment by gamecln277** [comment]
If look likes [this](https://github.com/wenxiaomao1023/scrcpy/blob/master/assets/out.gif)

**Comment by gamecln277** [comment]
I have a idea
If page design like [this](https://imgur.com/a/76TOfDV)
maybe it will looks very wonderful!
and last fix the drag and scale problem

**Comment by drauggres** [comment]
I think that these lines inserted [here](https://github.com/NetrisTV/ws-scrcpy/blob/master/src/DeviceConnection.ts#L114) should solve problem with drag (but I didn't test):
```javascript
document.body.ondragstart = function(e: MouseEvent): void {
    e.preventDefault();
    e.stopPropagation();
};
```
P.S. Or adding `draggable="false"` attribute to the elements.

**Comment by gamecln277** [comment]
`document.body.onmousedown = function(e: MouseEvent): void {
                down++;
                onMouseEvent(e);
            };
            document.body.onmouseup = function(e: MouseEvent): void {
                onMouseEvent(e);
                down--;
            };
            document.body.onmousemove = function(e: MouseEvent): void {
                onMouseEvent(e);
            };
            document.body.ondragstart = function(e: MouseEvent): void {
                e.preventDefault();
                e.stopPropagation();
            };
            this.hasListeners = true;
`

I insert them but nothing change QQ

draggable="false"
this IDK where can I insert ...

**Comment by santhoshbs1987** [comment]
> I think that these lines inserted [here](https://github.com/NetrisTV/ws-scrcpy/blob/master/src/DeviceConnection.ts#L114) should solve problem with drag (but I didn't test):
> 
> ```js
> document.body.ondragstart = function(e: MouseEvent): void {
>     e.preventDefault();
>     e.stopPropagation();
> };
> ```
> 
> P.S. Or adding `draggable="false"` attribute to the elements.

this did not work for me, please help with the working code

**Comment by santhoshbs1987** [comment]
> `document.body.onmousedown = function(e: MouseEvent): void { down++; onMouseEvent(e); }; document.body.onmouseup = function(e: MouseEvent): void { onMouseEvent(e); down--; }; document.body.onmousemove = function(e: MouseEvent): void { onMouseEvent(e); }; document.body.ondragstart = function(e: MouseEvent): void { e.preventDefault(); e.stopPropagation(); }; this.hasListeners = true; `
> 
> I insert them but nothing change QQ
> 
> draggable="false"
> this IDK where can I insert ...
> 
> [picture](https://imgur.com/a/QKLLDWD)

did you get the solution?

**Comment by pat993** [comment]
thanks for adding more feature, it now works on touch device, you guys did a great job
