### ISSUE TITLE
iOS compatibility issues with appium-xcuitest-driver 4.x

### ISSUE THREAD

**Issue by metocks** [NetrisTV/ws-scrcpy#215]
I can't connect my iOS device with ws-scrcpy for the following reasons:
- location: https://github.com/NetrisTV/ws-scrcpy/blob/master/src/server/appl-device/services/WDARunner.ts#L36
- reason: `XCUITest.startServer` is undefined

Meanwhile, this worked when using appium-xcuitest-driver 3.x version.
I hope it will be helpful to you.

**Comment by drauggres** [comment]
Hi.
Looks like they broke it in v4.5.0:
https://github.com/appium/appium-xcuitest-driver/blob/v4.5.0/index.js#L4

In v4.4.6 it was:
https://github.com/appium/appium-xcuitest-driver/blob/v4.4.6/index.js#L28

I didn't dig any further, but server.js is completely gone in v4.5.0.

**Comment by drauggres** [comment]
@metocks Can you try #216? (I don't have access to a mac/iphone).
