### ISSUE TITLE
When can I support Android 13 mobile phones?

### ISSUE THREAD

**Issue by changmiao007** [NetrisTV/ws-scrcpy#223]
When can I support Android 13 mobile phones?

**Comment by krishtoautomate** [comment]
@changmiao007 android 13 already working with both scrcpy and ws-scrcpy.

**Comment by changmiao007** [comment]
Google mobile phone is upgraded to the latest system and cannot be projected

**Comment by krishtoautomate** [comment]
Can you provide more details

**Comment by changmiao007** [comment]
Google pixel 6 Pro is updated to the latest version and cannot be projected

**Comment by changmiao007** [comment]
Updated the new agent to solve this problem. Thank you
