### ISSUE TITLE
Change the default device list URL

### ISSUE THREAD

**Issue by Arthurmtro** [NetrisTV/ws-scrcpy#226]
Hi !
I want to give device access to my users, but I don't want they to access the device list in the / URL
So can we change the default URL, for example '/devices' 

Thanks in advance

**Comment by drauggres** [comment]
Hi.
This project does not have any kind of user or permission management.
Also there are not other "routes" except `/`.

I'm not sure if it's possible to do what you want (properly) without implementing them and this is a lot of work.

In theory, you could add something like:
```typescript
if (location.pathname !== `/devices`) return;
```
After this lines:
https://github.com/NetrisTV/ws-scrcpy/blob/c95363100664ba08c82f281536767b853f54f18f/src/app/index.ts#L31-L34

And add `/devices` route to serve static files from `PUBLIC_DIR`, somethere around here:
https://github.com/NetrisTV/ws-scrcpy/blob/c95363100664ba08c82f281536767b853f54f18f/src/server/services/HttpServer.ts#L74-L76

But I'm not sure if it will work.

**Comment by Arthurmtro** [comment]
Would be an interesting feature in the future,
Or maybe throwing a full documentation about permission

But thanks for the fast responding mate
