### ISSUE TITLE
[NativeDecoder] Playback stops after settings changing

### ISSUE THREAD

**Issue by pigass0512** [NetrisTV/ws-scrcpy#23]
Hi master,

Now I got another question that after I clicked Native Decoder stream link and change video setting, the device stream had started, but after few seconds, the stream had stop... How can I fix it? Thanks!

**Comment by drauggres** [comment]
Hi. Yeah, I can reproduce it, will investigate.

**Comment by drauggres** [comment]
BTW, in my tests broadway decoder always was more efficient and stable than native.

**Comment by pigass0512** [comment]
> BTW, in my tests broadway decoder always was more efficient and stable than native.

I only can use Native as decoder, the other two still display black screen on my web page...haha this is my another question..

**Comment by hzms** [comment]
I have the same problem and only the native works, the other decoders are black screen

**Comment by drauggres** [comment]
@pigass0512 @hzms What operating system and browser do you have?

**Comment by pigass0512** [comment]
> @pigass0512 @hzms What operating system and browser do you have?

Hi master, windows 10 and chrome latest version.

**Comment by drauggres** [comment]
Tested on Chrome 83.0.4103.97 on Win10 x64, works fine here.

**Comment by pigass0512** [comment]
> Tested on Chrome 83.0.4103.97 on Win10 x64, works fine here.

I had upgrade Chrome version and Native stream become fluently, but the other two still black...

**Comment by drauggres** [comment]
> but the other two still black...
Try to move or open something, so picture on the screen is changed (I usually run clock/stopwatch for tests).
Encoder does not send frames when there are no changes on the screen (shouldn't be a problem on very first connection).

**Comment by pigass0512** [comment]
> > but the other two still black...
> 
> Try to move or open something, so picture on the screen is changed (I usually run clock/stopwatch for tests).
> Encoder does not send frames when there are no changes on the screen (shouldn't be a problem on very first connection).

The method seems not works for me, and the stream still stop playing in the few seconds..

**Comment by pigass0512** [comment]
Hi @drauggres master,
Does any update of this issue?

**Comment by drauggres** [comment]
Nope. No luck and no ideas.
Only thing I was able to find is that you can resize window (e.g. press F11 to open browser in fullscreen), press `change video settings` and player will unfreeze. But still don't why it freezes in the first place.

I'm thinking about different approach:
1. use original scrcpy instead of my fork
2. create web socket proxy server
3. configure all streaming parameters before connection

Downsides here are:
- unable to change video setting on the fly, it will require reconnection
- maybe be problems with simultaneous access of a device from more than one client (probably I can make it work)

**Comment by pigass0512** [comment]
Unfortunately, after I resize my device window, it still freeze in the further seconds..that's weird..

**Comment by drauggres** [comment]
I changed default frame rate value for native decoder. In my tests it is more stable now.

@pigass0512, please try again (`master` branch).

**Comment by drauggres** [comment]
> I have the same problem and only the native works, the other decoders are black screen

@hzms, @pigass0512, @jiahuanyu
Hey guys, try `develop` branch with broadway or tinyh264 decoders. If problem is still there, please open a new issue and specify OS, browser version and everithing that you think might be relevant.

**Comment by pigass0512** [comment]
Hi master @drauggres ,

After I pull develop branch and build the service, still only native decode can work..others are black screen..
I will open another issue for discuss with other decoder can not work problem, is that okay?

**Comment by drauggres** [comment]
> I will open another issue for discuss with other decoder can not work problem, is that okay?
Yes, please.
