### ISSUE TITLE
unable to call adb commands?

### ISSUE THREAD

**Issue by mindansung** [NetrisTV/ws-scrcpy#246]
Hello,

firstly, my apologies if this issue have come up before, but I couldn't find it and figure it out.

I am trying to put some simple buttons at the main front page to have logs automatically saved, files pushed, and to run a simple command from android devices.

but when I try to get the functions imported from '__src/server/goog-device/device.ts__'
or make my own function within '__src/app/googDevice/client/DeviceTracker.ts__', 
I get errors like 
`````
Uncaught Error: Cannot find module 'stream'
    at webpackMissingModule (transform.js:17:24)
`````
or
`````
Uncaught Error: Cannot find module 'fs'
    at webpackMissingModule (transform.js:17:24)
`````
and such.

Why is this happening and how can I possibly fix the issue?

Thank you in advance

**Comment by drauggres** [comment]
Hi.
I assume you have own webpack configuration. It should look something like this: https://github.com/NetrisTV/ws-scrcpy/blob/2d271d08a51ee36a09e6fea5b23d5d9d6c667b47/webpack/ws-scrcpy.common.ts#L134-L148

For the errors above the important part is `target: 'node'`

**Comment by mindansung** [comment]
Hello,

hoping you are having happy holidays.

The webpack configuration is exactly same as the one you have shown me as I have not changed anything with webpack configs, but still I get same error.

I have done some research and tried to fix the problem by changing the configs, but the most I got was errors displaying 
`````
Uncaught Error: Cannot find module 'stream'
`````

to 

`````
Uncaught Error: Cannot find module 'child_process'
`````

**Comment by drauggres** [comment]
Can you upload your project to github and post the command you use to build it?

**Comment by mindansung** [comment]
I will do so as soon as I get home today.

**Comment by mindansung** [comment]
I have posted the project to my github as ws-scrcpy-multi-device as public, and the commands I used to build it is
at root folder
`````
'npm run dist:dev'
'cd dist'
'node ./index.js'
`````
here is the simple button that calls for `adb deviecs`.(I also tried using child_process.spawn, but got same error)

https://github.com/mindansung/ws-scrcpy-multi-device/blob/69b7af87c3590a9c898b90e2052b426563c0b6cc/src/app/googDevice/client/DeviceTracker.ts#L263-L276

without adb command, the webpage works as intended for the moment, which is information of connected device and screen.

**Comment by drauggres** [comment]
The code inside `src/app` is running inside a browser. You can't use node modules (such as as `stream` or `child_process`) there.
Here is how it is done in this project:
- from client I send a command with specific code over WebSocket connection (e.g. [here](https://github.com/NetrisTV/ws-scrcpy/blob/2d271d08a51ee36a09e6fea5b23d5d9d6c667b47/src/app/googDevice/client/DeviceTracker.ts#L123-L141) is click handler which sends command to kill/restart server).
- the server will receive this websocket message [here](https://github.com/NetrisTV/ws-scrcpy/blob/2d271d08a51ee36a09e6fea5b23d5d9d6c667b47/src/server/goog-device/mw/DeviceTracker.ts#L81)
- and will pass it [here](https://github.com/NetrisTV/ws-scrcpy/blob/2d271d08a51ee36a09e6fea5b23d5d9d6c667b47/src/server/goog-device/services/ControlCenter.ts#L158-L179)

**Comment by mindansung** [comment]
happy new years and thank you so much! 
I have been going through the codes and saw the commands and such, but I simply couldn't sew them together enough to make them work.

Now, I can work with them to produce what I want and how it is processed.

Thank you once again!
