### ISSUE TITLE
Only MseDecoder can work, other decoders display black screen.

### ISSUE THREAD

**Issue by pigass0512** [NetrisTV/ws-scrcpy#25]
As title, only native decoder can work in my environment, the other three decoder display black screen after I launch the web page.
Can someone help to check this out?

Chrome version: 83.0.4103.116
Desktop OS: Windows 10
NPM version: 6.14.5
NODE version: 8.17.0

**Comment by drauggres** [comment]
To be clear, all three other decoders work for me on mac/linux/windows on chrome/firefox and safari. I don't know where to look at.
Any help or additional info (maybe there are logs in the console in dev-tools) appreciated.
<details>
  <summary>Screenshot. Win10/Chrome 83</summary>

![ws-scrcpy](https://user-images.githubusercontent.com/7796592/87581710-11b1e080-c6e2-11ea-8002-b8ea31b05de2.png)

</details>

**Comment by LeeGenD** [comment]
This situation may be caused by a special device(Android mobile phone), because the three decoders work for my first device, but not work for another.
Another reason is because broadway.js only support low quality video streaming.

**Comment by drauggres** [comment]
@LeeGenD @pigass0512
Can you share the first two video frames that come over the websocket?
They have `0000 0001 67` and `0000 0001 65` bytes at the beginning.
<details>
  <summary>Screenshot. </summary>


![websoket-messages](https://user-images.githubusercontent.com/7796592/93712271-83346200-fb5d-11ea-87a7-b2881f3c92d0.png)

</details>

**Comment by drauggres** [comment]
Also please try to change this line to `const CODEC_OPTIONS = 'profile=1,level=1';`:
https://github.com/NetrisTV/ws-scrcpy/blob/79098c69773cded80b58a4f0e7528fc4cbc9cdcd/src/server/Constants.ts#L17

You will need  kill `app_process`, this parameter is passed as an argument to the scrcpy-server.

**Comment by pigass0512** [comment]
> @LeeGenD @pigass0512
> Can you share the first two video frames that come over the websocket?
> They have `0000 0001 67` and `0000 0001 65` bytes at the beginning.
> 
> Screenshot.
> Upd: base64 is prefered.

Hi master,

But I can not using any decoders after I build the service with v0.4.1.....OMG!!

**Comment by drauggres** [comment]
> But I can not using any decoders after I build the service with v0.4.1.....OMG!!
> I had reboot my device and using the same wifi network, but still cannot launch the screenshot....lol

After reboot do you open "device list" page first or directly `/#!action=stream&`? Server is installed after devices detection, which happens only when "device list" page requested.

**Comment by pigass0512** [comment]
> > But I can not using any decoders after I build the service with v0.4.1.....OMG!!
> > I had reboot my device and using the same wifi network, but still cannot launch the screenshot....lol
> 
> After reboot do you open "device list" page first or directly `/#!action=stream&`? Server is installed after devices detection, which happens only when "device list" page requested.

Hi master,

My steps as below :
1. Reboot my mobile device.
2. Git clone the project with v0.4.1
3. npm install and start the service.
4. Go to Device list web page.
5. Click one of decoder in list.

**Comment by drauggres** [comment]
> Also please try to change this line to `const CODEC_OPTIONS = 'profile=1,level=1';`:
> https://github.com/NetrisTV/ws-scrcpy/blob/79098c69773cded80b58a4f0e7528fc4cbc9cdcd/src/server/Constants.ts#L17
> 
> You will need kill `app_process`, this parameter is passed as an argument to the scrcpy-server.

Tried on OnePlus 6 (Android 10): with `profile=1,level=1` Broaway and TinyH264 work just fine.
Will add fix to the next release.

**Comment by tulasikrishan89** [comment]
same is happening to me as well. MSE decoder is working and other screens showing black

**Comment by MartinRGB** [comment]
> > Also please try to change this line to `const CODEC_OPTIONS = 'profile=1,level=1';`:
> > https://github.com/NetrisTV/ws-scrcpy/blob/79098c69773cded80b58a4f0e7528fc4cbc9cdcd/src/server/Constants.ts#L17
> > 
> > You will need kill `app_process`, this parameter is passed as an argument to the scrcpy-server.
> 
> Tried on OnePlus 6 (Android 10): with `profile=1,level=1` Broaway and TinyH264 work just fine.
> Will add fix to the next release.
> 
> UPD: but it breaks encoder on some devices with android 6...

works,better write in README.MD

**Comment by drauggres** [comment]
Using these options by default is not an options.
I'm thinking about using `profile=1,level=1` automatically on Android 10+ and keeping `-` for others, but I haven't decided yet.
Also I want to add possibility to change "codec options" (and new [`encoder`](https://github.com/Genymobile/scrcpy#encoder)  parameter) at runtime same way as video settings.

**Comment by drauggres** [comment]
I have implemented a configuration dialog in the [`develop`](https://github.com/NetrisTV/ws-scrcpy/tree/develop) branch.
Now, before opening the stream, you can configure video settings, including codec options and encoder.

Changing encoder look like a simpler solution than setting codec options.

If anyone can test it, please let me know the results.

**Comment by drauggres** [comment]
To summarize:
1. Broadway.js and Tiny H264 are capable to decode only video encoded with Baseline profile
2. To change profile you can:
- specify codec option (not necessary exactly `profile=1,level=1`, but it seems to work in some cases, for more information see `--codec-options` option in scrcpy)
- select different encoder (hoping it has Baseline as default profile)

Otherwise you can use [`MSE`](https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API) based player, at the momen we use here [xevokk/h264-converter](https://github.com/xevokk/h264-converter).
