### ISSUE TITLE
error: no member named 'AccessorSignature' in namespace 'v8'

### ISSUE THREAD

**Issue by ai2online** [NetrisTV/ws-scrcpy#250]
after I run  npm install , interrupt at these:
In file included from ../src/unix/pty.cc:20:ing reifyNode:node_modules/lodash Completed in 23018ms
In file included from ../../nan/nan.h:180:
../../nan/nan_callbacks.h:55:23: error: no member named 'AccessorSignature' in namespace 'v8'
typedef v8::Local<v8::AccessorSignature> Sig;

**Comment by ai2online** [comment]
ok,i had solved it。
after run cd ws-scrcpy
run command
npm install nan@2.17 --save

**Comment by sarfarazengglb** [comment]
Lovely it is working thank you bro @ai2online
