### ISSUE TITLE
Keyboard mapping

### ISSUE THREAD

**Issue by stoefln** [NetrisTV/ws-scrcpy#259]
Hey there,

I noticed that my german keyboard is not mapping correctly. E.g. when I want to type a "@" I need to press shift+2, instead of option+l. Umlaute (such as "ÖÄÜ") can also not be sent.
Any advice on how this could be fixed?
I am fine to dig through the code and find the right spot for the tweak. But if you help me to understand where that is, that would be amazing!
Interesting: If I log the JS keyevents, the map correctly. So they correspond to whats actually printed on my keyboard-keys.
So it seems scrcpy is interpreting the keys in the wrong way. At least that's what I currently think...

**Comment by drauggres** [comment]
Hi.

https://github.com/NetrisTV/ws-scrcpy/blob/master/src/app/googDevice/KeyInputHandler.ts#L14

https://blog.rom1v.com/2018/03/introducing-scrcpy/#handle-text-input

**Comment by stoefln** [comment]
Thank you!
