### ISSUE TITLE
Device Feed is not shown when I click Broadway/Native/h264bsd on Chrome/Firefox

### ISSUE THREAD

**Issue by vickipedia** [NetrisTV/ws-scrcpy#26]
<details>
  <summary>Screenshot.</summary>

![image](https://user-images.githubusercontent.com/10095433/88415484-34d44280-cdfc-11ea-8939-e41df301391c.png)

</details>

Not sure what I'm missing, but I'm not able to see my device screen when I click on the feed options. Logcat and Shell works just fine.

Tried two different devices running Android Pie. Same observation.

**Comment by drauggres** [comment]
Hi.
Screen streaming works over network, where logcat and shell work over adb (usb by default).
Verify that you have wifi enabled on your devices and that there is correct IP-address in the `ip` parameter in the URL.

**Comment by vickipedia** [comment]
I somehow missed the port forwarding part and using 127.0.0.1 worked. Thanks!
