### ISSUE TITLE
Cannot find name 'ReadableStreamDefaultReadResult'. Did you mean 'ReadableStreamDefaultReader'?

### ISSUE THREAD

**Issue by vanxv** [NetrisTV/ws-scrcpy#267]
ERROR in /Users/xucongyong/temp/ws-scrcpy/src/app/client/BaseClient.ts
5:71-73
[tsl] ERROR in /Users/xucongyong/temp/ws-scrcpy/src/app/client/BaseClient.ts(5,72)
      TS2344: Type 'TE' does not satisfy the constraint 'EventMap'.
ts-loader-default_e3b0c44298fc1c14

ERROR in /Users/xucongyong/temp/ws-scrcpy/src/app/googDevice/filePush/FilePushHandler.ts
55:16-47
[tsl] ERROR in /Users/xucongyong/temp/ws-scrcpy/src/app/googDevice/filePush/FilePushHandler.ts(55,17)
      TS2552: Cannot find name 'ReadableStreamDefaultReadResult'. Did you mean 'ReadableStreamDefaultReader'?

**Comment by ctaoist** [comment]
我也遇到了这个问题，老哥，你是怎么解决的啊

**Comment by drauggres** [comment]
I guess the problem is caused by a newer `@types`. Try to install dependencies with `npm ci`.
