### ISSUE TITLE
cant get any live stream in browser

### ISSUE THREAD

**Issue by LiorLPerfecto** [NetrisTV/ws-scrcpy#27]
MacOS - Catalina
Browser - Chrome: Version 84.0.4147.89 (Official Build) (64-bit)
Real device - galaxy note 9 - android 10

**Comment by LiorLPerfecto** [comment]
Found why: 
When opening the stream tub there is missing parameter : 
http://127.0.0.1:8000/#!showFps=true&action=stream&udid=###########&decoder=native&ip=&port=8886
NO ip address

**Comment by LiorLPerfecto** [comment]
by the way - another issue but seems like video is tend to freeze after a few seconds - randomly

**Comment by drauggres** [comment]
Hi.

> NO ip address

Verify that you have Wi-Fi enabled on the device.

> by the way - another issue but seems like video is tend to freeze after a few seconds - randomly

Try other decoders, there are 4 of them now in `develop` branch (the least problematic in my tests was Broadway).
