### ISSUE TITLE
How to change default screen size?

### ISSUE THREAD

**Issue by pigass0512** [NetrisTV/ws-scrcpy#28]
Hi master @drauggres ,

The default screen size of the width is 208px and the height is 480px when I launch native decoder.
How do I modify the script to change default screen size to bigger? (not using click "Change video settings" button to make screen bigger than default)
Thanks!

**Comment by drauggres** [comment]
Hi.
For native decoder it should be limited to [720px](https://github.com/NetrisTV/ws-scrcpy/blob/develop/src/decoder/NativeDecoder.ts#L11). You can change it in the code: each decoder has `preferredVideoSettings.maxSize`. This property work as [max-size](https://github.com/Genymobile/scrcpy#reduce-size) in the original scrcpy.

Also I added [here](https://github.com/NetrisTV/ws-scrcpy/commit/15493b8dfc9e942d7dc99eaf790426e9312a3c17) (only in `develop` brunch for now) saving settings to the local storage, so it will remember settings after you changed them. Be aware that `scrcpy-server.jar` version in this branch is not compatible with previous versions, you will need to kill the process manually (or restart the device).

**Comment by drauggres** [comment]
@pigass0512  please check `develop`, now it should fine.

**Comment by drauggres** [comment]
Merged into `master`. Released as [v0.3.0](https://github.com/NetrisTV/ws-scrcpy/releases/tag/v0.3.0)
