### ISSUE TITLE
issues with Android 14

### ISSUE THREAD

**Issue by krishtoautomate** [NetrisTV/ws-scrcpy#282]
screen only appearing sometimes.

interactions not working.

scrcpy is working fine

**Comment by krishtoautomate** [comment]
https://github.com/Genymobile/scrcpy/pull/4075

**Comment by krishtoautomate** [comment]
@drauggres is it possible for you to add patch for this issue?

I tried to fix it but this(https://github.com/NetrisTV/scrcpy) fork is way behind to pull changes

**Comment by krishtoautomate** [comment]
also making complete changes to scrcpy original is not a good idea.

only additions should be websocket classes and extra methods in server and desktop connection class similar to below changes:
https://github.com/Genymobile/scrcpy/pull/4154/files


Just a thought. to keep this project live longer. thanks

**Comment by krishtoautomate** [comment]
working now.

**Comment by ahmadt1919** [comment]
what did you change to get this work. i am having the similar issues

**Comment by krishtoautomate** [comment]
Not working on some brands of devices for 14. To consume scrcpy 2.0 huge refactoring is required.

**Comment by ahmadt1919** [comment]
would you be interested in being hired to refactor it?

**Comment by ahmadt1919** [comment]
Let me know I have a budget to get this done

**Comment by krishtoautomate** [comment]
[scrcpy-server15.zip](https://github.com/user-attachments/files/16443637/scrcpy-server15.zip)
you can try this

**Comment by eschoenawa** [comment]
@krishtoautomate just replace the scrcpy-server.jar in the ws-scrcpy/vendor/Genymobile/scrcpy folder? Or does this need further changes? Because that didn't work for me unfortunately.
