### ISSUE TITLE
Found 1 error while running "npx tsc -p . "

### ISSUE THREAD

**Issue by HussainMehdi** [NetrisTV/ws-scrcpy#3]
C:\Users\Hussain\Desktop\ws-scrcpy>npx tsc -p .
src/h264-live-player/WebGLCanvas.ts:226:13 - error TS2322: Type 'CanvasRenderingContext2D | ImageBitmapRenderingContext | WebGLRenderingContext | WebGL2RenderingContext | null' is not assignable to type 'WebGLRenderingContext | null | undefined'.
  Type 'CanvasRenderingContext2D' is missing the following properties from type 'WebGLRenderingContext': drawingBufferHeight, drawingBufferWidth, activeTexture, attachShader, and 429 more.

226             this.gl = this.canvas.getContext('experimental-webgl');
                ~~~~~~~

**Comment by drauggres** [comment]
Hi @HussainMehdi. Please try with latest `master`, should work now.
(somehow typechecking became stricter)
