### ISSUE TITLE
use of ethernet ip not possible

### ISSUE THREAD

**Issue by ChaosEmpire** [NetrisTV/ws-scrcpy#32]
switched my devices to a 64bit OS, which has no longer support for wifi chip
devices connected now via ethernet

there is no way to stream, as only wifi ip is used
ethernet ip , if present, should be used as first option, even when wifi is present

**Comment by ChaosEmpire** [comment]
forget about my brain fart
as i m able to conenct to shell, its using the right ip from eth

the question is, why is no longer any stream available

**Comment by drauggres** [comment]
Hi. 

I use this project only with mobile phones and never tested it on devices with ethernet interface.
When there is no `Wi-Fi IP` or `PID` in the device list, no "stream" links are displayed.

You can change interface name [here](https://github.com/NetrisTV/ws-scrcpy/blob/5f0881ca311a7ff63132600f306e2925002e2325/src/server/ServerDeviceConnection.ts#L188). But AFAIK there is no property for ethernet interface (for Wi-FI there is `wifi.interface`: `adb shell getprop wifi.interface`), so you will need to detect it somehow (most likely it will be `eth0`).
