### ISSUE TITLE
Drag & Drop begins but does not proceed further

### ISSUE THREAD

**Issue by vickipedia** [NetrisTV/ws-scrcpy#33]
Tried to drag and drop an APK file to connected device. It shows the "begin..." message but does not proceed any further. I tried introducing logs to see where it gets stuck and it seems its stuck waiting for response in the below code snippet.

Commit: Master 5f0881c

Code Snippet (lines 65-71):

File: FilePushHandler.ts

        this.sendUpdate({ pushId: id, fileName, logString: 'begin...', error: false });
        const newParams = { id, state: FilePushState.NEW };
        this.connection.sendEvent(CommandControlEvent.createPushFileCommand(newParams));
        const pushId: number = await this.waitForResponse(id); // gets stuck here
        if (pushId <= 0) {
            this.logError(pushId, fileName, pushId);
        }

Not sure if I'm missing something here. The APK file size is relatively small (111 KB), so I hope the file size should not be causing this. This issue is reproducible in at least couple of devices from different vendors. (OnePlus 7 being one)

Also tried with different APKs and checked if the file was uploaded to public folder. No luck there as well.

**Comment by drauggres** [comment]
Hi. Please try code from [develop](https://github.com/NetrisTV/ws-scrcpy/tree/develop) branch.
There was a small problem in the server, so you will need to kill `app_process` on your device or just reboot it.

**Comment by vickipedia** [comment]
Issue is not reproducible in develop branch. Closing. Thanks!
