### ISSUE TITLE
black border appeared on the top and bottom of the screen

### ISSUE THREAD

**Issue by wangfuyangsau** [NetrisTV/ws-scrcpy#37]
When I tested it on my phone, the black border appeared on the top and bottom of the screen. What is the problem? What should I do?

**Comment by drauggres** [comment]
Does this problem appear in the original scrcpy?
If not, please attach a screenshot (or does it happen on the device?), I have never seen anything like what you describe.

**Comment by wangfuyangsau** [comment]
<img width="957" alt="untitled" src="https://user-images.githubusercontent.com/38742841/93762607-7e95a980-fc42-11ea-8eee-efbca563180a.png">
There was no problem with the original scrcpy, and some other phones did not have this problem.

**Comment by drauggres** [comment]
Does it happen on all included decoders? Also what is the screen resolution of this device?

**Comment by wangfuyangsau** [comment]
I will try different decoders and check the resolution of the screen later. Thank you very much for your answer. I will contact you again if there is any question.

**Comment by wangfuyangsau** [comment]
In my tests, only Msedecoder was able to get images, and the device's resolution was 1080x2340.

**Comment by drauggres** [comment]
It possible that video tag size does not match actual video size (like than you watch 16:9 video on 4:3 screen you will see the same).

Can you open developer tools while streaming and run in the console this:
```
var {videoWidth, videoHeight, clientWidth, clientHeight} = document.getElementsByTagName('video')[0];
console.log({videoWidth, videoHeight, clientWidth, clientHeight})
```
I tried with android emulator (with 1080x2340 resolution), but wasn't able to reproduce: `videoWidth` and `videoHeight` were always the same as `clientWidth` and `clientHeight` respectively.

As for only MseDecoder working, can you try https://github.com/NetrisTV/ws-scrcpy/issues/25#issuecomment-695804670, and post your results there?

**Comment by wangfuyangsau** [comment]
`// return the optimal size of the window, with the following constraints:
//  - it attempts to keep at least one dimension of the current_size (i.e. it
//    crops the black borders)
//  - it keeps the aspect ratio
//  - it scales down to make it fit in the display_size
static struct size
get_optimal_size(struct size current_size, struct size content_size) {
    if (content_size.width == 0 || content_size.height == 0) {
        // avoid division by 0
        return current_size;
    }

    struct size window_size;

    struct size display_size;
    if (!get_preferred_display_bounds(&display_size)) {
        // could not get display bounds, do not constraint the size
        window_size.width = current_size.width;
        window_size.height = current_size.height;
    } else {
        window_size.width = MIN(current_size.width, display_size.width);
        window_size.height = MIN(current_size.height, display_size.height);
    }

    if (is_optimal_size(window_size, content_size)) {
        return window_size;
    }

    bool keep_width = content_size.width * window_size.height
                    > content_size.height * window_size.width;
    if (keep_width) {
        // remove black borders on top and bottom
        window_size.height = content_size.height * window_size.width
                           / content_size.width;
    } else {
        // remove black borders on left and right (or none at all if it already
        // fits)
        window_size.width = content_size.width * window_size.height
                          / content_size.height;
    }

    return window_size;
}`
In the native scrcpy screen.c, I found this function and wonder if you have the same treatment in your project.

**Comment by wangfuyangsau** [comment]
![无标题](https://user-images.githubusercontent.com/38742841/93994293-4ddc7e00-fdc2-11ea-9571-c80d3455b28b.png)
In the native scrcpy screen.c, I found this function and wonder if you have the same treatment in your project.

**Comment by drauggres** [comment]
Not the same:
1. This project doesn't handle window resizing, everyting below happens only after the start or after `Change video settings` button is pressed.
2. Client receives `ScreenInfo` from the server: https://github.com/NetrisTV/ws-scrcpy/blob/79098c69773cded80b58a4f0e7528fc4cbc9cdcd/src/DeviceConnection.ts#L297-L298 and applies it to Decoder 
3.1 For MseDecoder video tag size is not limited, but only size of its parent element: https://github.com/NetrisTV/ws-scrcpy/blob/79098c69773cded80b58a4f0e7528fc4cbc9cdcd/src/decoder/Decoder.ts#L203-L217
3.2 For other ("canvas based") decoders, the canvas is also resized: https://github.com/NetrisTV/ws-scrcpy/blob/79098c69773cded80b58a4f0e7528fc4cbc9cdcd/src/decoder/CanvasCommon.ts#L145-L151

The actual video size is never checked, as it is expected to match the value received in `ScreenInfo` earlier, that is why I asked you run: 
```
var {videoWidth, videoHeight, clientWidth, clientHeight} = document.getElementsByTagName('video')[0];
console.log({videoWidth, videoHeight, clientWidth, clientHeight})
```
so we could compare them.

P.S. you can post multiline code by surrounding it with triple backtick (\`), or include direct permalink to github, e.g.:
`https://github.com/NetrisTV/ws-scrcpy/blob/79098c69773cded80b58a4f0e7528fc4cbc9cdcd/src/decoder/CanvasCommon.ts#L145-L151`
