### ISSUE TITLE
[Question][Research] Audio support

### ISSUE THREAD

**Issue by ChinaLiuKang** [NetrisTV/ws-scrcpy#38]
I want to develop audio based on the project, where should I start first?

**Comment by drauggres** [comment]
Hi.
1. Examine https://github.com/rom1v/sndcpy (or maybe there are other similar project)
2. Find out what audio format it produces: compare it with https://en.wikipedia.org/wiki/HTML5_audio, to confirm that it is supported by your targer browser (also [this](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs) could be helpful)
3. If you want to send audio data over Web Socket (as video data sent here), you may want to integrate WebSocket server into sndcpy jar (as I did with scrcpy: https://github.com/NetrisTV/scrcpy/tree/feature/websocket-v1.16.x) or write a standalone WS server yourself (for example on node.js)
4. Read about [Media Source Extensions](https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API)
5. Look at https://github.com/samirkumardas/jmuxer, for example

**Comment by ChinaLiuKang** [comment]
These suggestions have helped me a lot, thank you very much!!!

**Comment by ChinaLiuKang** [comment]
Have you ever thought about connecting audio into the project?

**Comment by drauggres** [comment]
You are welcome.
No, I don't really need audio for my use case, but if you manage to make it work - let me know and feel free to send a PR.

**Comment by ChinaLiuKang** [comment]
ok！！！
