### ISSUE TITLE
Any suggesting how to expose to internet

### ISSUE THREAD

**Issue by guydoron** [NetrisTV/ws-scrcpy#43]
I have ngrok tunneling port 8000. On local wife it works great but outside on the internet I do get the dashboard webpage, but no streaming link works ...

**Comment by guydoron** [comment]
Manage to expose. There is a need to also expose the stream ip. But if there is a better way. Would love to hear

**Comment by drauggres** [comment]
You can try [develop](https://github.com/NetrisTV/ws-scrcpy/commits/develop) branch.
It has `proxy over adb` option in the interfaces list: video stream and control commands are proxied over 8000 port.
I was thinking about emulators when I implemented it, but it will work for your case too.

**Comment by drauggres** [comment]
And as a reminder: [Security warning](https://github.com/NetrisTV/ws-scrcpy#security-warning).

**Comment by drauggres** [comment]
> You can try [develop](https://github.com/NetrisTV/ws-scrcpy/commits/develop) branch.
> It has `proxy over adb` option in the interfaces list: video stream and control commands are proxied over 8000 port.
> I was thinking about emulators when I implemented it, but it will work for your case too.

Released as v0.6.0
