### ISSUE TITLE
No stream is displayed: windows Server 2016, Android 8.1

### ISSUE THREAD

**Issue by mtimti** [NetrisTV/ws-scrcpy#44]
Hi, 

after successful starting the  frontend , no stream (any decoder) is starting
Listening on: http://xyz:8000 http://[xxx:xx:xxxx:xxxx:xxx]:8000 http://xx.xx.xx.xx:8000 http://[::1]:8000 http://127.0.0.1:8000
[xx.xx.xx.xx:5555] failed to spawn adb process spawn adb ENOENT
Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[xx.xx.xx.xx:5555] adb process (-s xx.xx.xx.xx:5555 shell CLASSPATH=/data/local/tmp/scrcpy-server.jar nohup app_process / com.genymobile.scrcpy.Server 1.16-ws1 ERROR 0 8000000 60 -1 false - false true 0 false false - web 8886 2>&1 > /dev/null) exited with code -4058
[xx.xx.xx.xx:5555] error: failed to start server

http://127.0.0.1:8000/#!action=stream&udid=xx.xx.xx.xx%3A5555&decoder=broadway&ip=xx.xx.xx.xx&port=8886

- windows server 2016
- node.js v12.18.4
- Chrome  85.0.4183.102 (Offizieller Build) (32-Bit)
- scrcpy-win64-v1.16 is working fine with adb over tcp
- Android 8.1, SDK 27, wifi is on

Do you have any suggestions?

Thanks

**Comment by drauggres** [comment]
Are you sure `adb` is available in the $PATH?

**Comment by drauggres** [comment]
`scrcpy-win64-v1.16` includes `adb.exe`, but this project does not.
Preferable way to get it is to install [android platform tools](https://developer.android.com/studio/releases/platform-tools).

**Comment by mtimti** [comment]
Thanks, that helped
