### ISSUE TITLE
android client without nodejs server

### ISSUE THREAD

**Issue by blackfa1con** [NetrisTV/ws-scrcpy#45]
Hello 
I'm building a ws-scrcpy android client, but i have problem when i try to connect to the web socket.
when i use for example the ffplay binary to test the stream i get:

> [http @ 00000241da680540] HTTP error 404 WebSocket Upgrade Failure
http://192.168.1.9:8886: Server returned 404 Not Found

how can i access the stream without nodejs server?

as i understand the server need to get a socket request from client with a magic string to accept the connection.

Thank you for this project.

**Comment by drauggres** [comment]
Hi.

scrcpy-server.jar used in this project streams video over WebSocket, not HTTP (and stream also includes internal commands, not only video)
You can't use ffplay to play it.

What are you trying ot achieve?

**Comment by blackfa1con** [comment]
> Hi.
> 
> scrcpy-server.jar used in this project streams video over WebSocket, not HTTP (and stream also includes internal commands, not only video)
> You can't use ffplay to play it.
> 
> What are you trying to achieve?

Oh i understand thank you.
 
Can i have your email to give you idea about my project?

**Comment by drauggres** [comment]
> Can i have your email to give you idea about my project?

Is it a secret project? :-) I prefer github, so everyone will be able to find answers for common questions.

My email included in every single commit in this project (e.g. [last](https://github.com/NetrisTV/ws-scrcpy/commit/34792fbad71a059e2c84700dd8f460759d8f792d.patch))

**Comment by blackfa1con** [comment]
It's not secret :D, but its need a lot of lines to make you understand my goal.
Thank you alot.

**Comment by drauggres** [comment]
> Hello
> By your instructions, my android client for your websocket server is now running well ♡
> I disabled some codes inside the DeviceController.ts to keep only the video layer..
> But i can't understand why i cant change the video ( W,H ) in the video layer ...
> If i use the command wm size on the development board i see the size will changed
> In the video layer...
> Can i keep the board screen size and make the video layer inside the android client webview stretch ?
> Or make the video layer full screen, even if the resolution decreases.
> Thank you alot for your time.

Hi, @blackfa1con.

I don't think scrcpy supports screen resizing (https://github.com/Genymobile/scrcpy/issues/161).
But since you are using a web client you can simply reload the page, it will cause reinitialization of screenencoder and client always tries to fit the video into the available space on start.

P.S. lets keep conversation here, it's much easier for me, if you don't mind
