### ISSUE TITLE
Controlling video/canvas size

### ISSUE THREAD

**Issue by guydoron** [NetrisTV/ws-scrcpy#46]
Cloud not find a way to control video/screen size in code. I did change each decoder bounds: new Size(720, 720), 
nothing changed video/canvas is very small.

**Comment by drauggres** [comment]
You need to create new `VideoSettings` instance with desired `bounds` value, then pass it to `CommandControlMessage.createSetVideoSettingsCommand` as argument and send the returned command.
https://github.com/NetrisTV/ws-scrcpy/blob/34792fbad71a059e2c84700dd8f460759d8f792d/src/app/client/ScrcpyClient.ts#L192-L195

`bound` value in `preferredVideoSettings` in decoders is overwritten here:
https://github.com/NetrisTV/ws-scrcpy/blob/34792fbad71a059e2c84700dd8f460759d8f792d/src/app/client/ScrcpyClient.ts#L99-L111

**Comment by guydoron** [comment]
Thank you, Would it affect HTML as well to create the video/canvas to be the same size?

**Comment by drauggres** [comment]
Server will send a reply with new VideoSettings (same message as one on the start) and these setting will be applied to decoder and video/canvas tags.

**Comment by guydoron** [comment]
Great That Worked!
