### ISSUE TITLE
Hi, how can I connect to a remote android device?

### ISSUE THREAD

**Issue by JonahLyu** [NetrisTV/ws-scrcpy#47]
It seems I have to run the `adb connect <host>:<port>` on the server host to enable the connection every time. Is there a way to auto connect to the device by inputing the device host and port in the form of query?

So is like, `http://127:0.0.1:8000/?...&host=<device host>&port=<device port>...`, to auto adb the remote device and get the stream.

Is it possible?

**Comment by drauggres** [comment]
Hi.
There is no such feature now: all my test devices are connected via USB.
But this can be implemented with little effort (assuming adb on device already listens for a tcp/ip connection).

Worth to notice:
1. to connect adb to device over Wi-Fi (on Android 10 and lower) you must connect it with usb first
2. `ws-scrcpy` server detects all connected devices and runs `scrcpy-server.jar` on them
3. `scrcpy-server.jar` will keep running after device disconnection (not like the original scrcpy), i.e. you still can connect to the stream (if you know ip-address of the device)

**Comment by JonahLyu** [comment]
I finally made it. this is what I try:
In `typings/@devicefarmer/adbkit/index.d.ts`, add the following interfaces in AdbKitClient:

```javascript
export interface AdbKitClient {
    //other interfaces
    forward(serial: string, local: string, remote: string, callback?: Callback<true>): Promise<true>;
    connect(host: string, port?: string, callback?: Callback<string>): Promise<string>;   //add this line
    disconnect(host: string, port?: string, callback?: Callback<string>): Promise<string>; //add this line as well
}

```

Then in `src/server/Util.ts`, amend the `Util.foward()` method. Add the adb connect so it tries to establish a new connection before it searches existing adb forward:

```javascript
public static async forward(serial: string, remote: string): Promise<number> {
        const client = ADB.createClient();

        //add following lines
        serial = await client.connect(serial);
        console.log(`connect to ${serial}`);
        //add above lines
     
        const forwards = await client.listForwards(serial);
        ...
        return port;
    }
```

But the known issue now is:
**how to disconnect the adb automatically when the websocket closes?** 

Any hint?

**Comment by drauggres** [comment]
It would be convenient to add the following actions before this line (not in the `forward` method):
https://github.com/NetrisTV/ws-scrcpy/blob/eb296728db2fa3a229fc4d321e6d3a4a4cb463b6/src/server/index.ts#L125-L126
1. Check if the device already connected
2. If it is not:
2.1 call `client.connect(..)`
2.2 add `ws.onclose = () => { client.disconnect(..); }`

P.S. In `develop` branch I have complete typings for `adbkit`.
