### ISSUE TITLE
[ws-qvh] Scale calculation issue

### ISSUE THREAD

**Issue by egegrsn** [NetrisTV/ws-scrcpy#48]
While using ws-qvh, there is a scale calculation issue, which causes clicking coordinate mistakes.

**Comment by drauggres** [comment]
Hello again :-).

Here is what I need from you:

1. open devtools for a "stream page"
2. run `var {videoWidth, videoHeight} = document.getElementsByTagName('video')[0]; console.log({videoWidth, videoHeight})` in devtools console
3. open "network" tab in devtools
4. click in the top-left, then bottom-right corners of the video

Paste here:
1. output from the second step
2. response for `GET wda/screen` request
3. request payloads for two `POST wda/touch/perform`

For `iPhone 11 Pro` I got:
1. `{videoWidth: 1126, videoHeight: 2436}`
2.  
```json
{
  "value" : {
    "statusBarSize" : {
      "width" : 375,
      "height" : 44
    },
    "scale" : 3
  },
  "sessionId" : "DFA28E6E-0B23-4AF1-B352-9B6ED8CBB7E0"
}
```
3. 
```json
{"actions":[{"action":"tap","options":{"x":2,"y":2}}]}
```
```json
{"actions":[{"action":"tap","options":{"x":373,"y":811}}]}
```

<details>
  <summary>Screenshot. wda/screen
 </summary>


![wda-screen](https://user-images.githubusercontent.com/7796592/99402355-52bd3a00-28fa-11eb-97ab-99e04e6a7ab5.png)
</details>

<details>
  <summary>Screenshot. wda/touch/perform
 </summary>

![wda-touch](https://user-images.githubusercontent.com/7796592/99402487-74b6bc80-28fa-11eb-86c1-1cecc07a5418.png)


</details>

**Comment by egegrsn** [comment]
For iPhone 7 Plus I got:

1. {videoWidth: 1080, videoHeight: 1920}
2. 
```
{
  "value" : {
    "statusBarSize" : {
      "width" : 414,
      "height" : 20
    },
    "scale" : 3
  },
  "sessionId" : "CAAB2212-6AEF-4709-922F-8DBAEF92CAFE"
}
```

3. `{actions: [{action: "tap", options: {x: 3, y: 3}}]}`
    `{actions: [{action: "tap", options: {x: 356, y: 636}}]}`

**Comment by egegrsn** [comment]
Hi, have you found anything about this issue?

**Comment by drauggres** [comment]
Did you try with `develop` branch? Looks like this problem has already been fixed there.

In `master`: `width = videoWidth / scale; height = videoHeight / scale; // (360 x 640)`
In `develop`: `width = statusBarSize.width; height = videoHeight / (videoWidth / statusBarSize.width); // (414 x 736)`

https://developer.apple.com/library/archive/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/Displays/Displays.html

**Comment by egegrsn** [comment]
Hi, I have tried develop branch. Bottom side of the UI does not work properly. I can't click anything from dock.

I tried to clone develop branch like
`git clone -b develop https://github.com/NetrisTV/ws-scrcpy.git`

**Comment by drauggres** [comment]
>I tried to clone develop branch like
git clone -b develop https://github.com/NetrisTV/ws-scrcpy.git

OK, this will work too (you could checkout to `develop` without cloning everything again).

Unfortunately I can't debug it without a real device. You'll have to deal with it yourself.
For a start you can check coordinates (as you did before) and verify, that they are in the correct range (`[0; 414]`, `[0; 736]`).
Then try to install [Appium Desktop](https://github.com/appium/appium-desktop) and see what coordinates it generates for clicks on the dock.

P.S. you rebuilt frontend after switching to develop, right? (`npm install`;`npm run dist:qvhack:frontend`)
