### ISSUE TITLE
 ServerDeviceConnection error (Window version with fix/win)

### ISSUE THREAD

**Issue by pdj14** [NetrisTV/ws-scrcpy#5]
Now I am try to show my target by web, for this I found this solution in Git. 
it's Good for me but I met some issue like under comments. 

dbug ADB Running 'D:\Android\Sdk\platform-tools\adb.exe -P 5037 -s R39KC04P6W shell 'ip route|grep wlan0|grep -v default''
ERR! ServerDeviceConnection Error: Command 'D:\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s R39KC04P6W shell 'ip route|grep wlan0|grep -v default'' exited with code 1
ERR! ServerDeviceConnection     at ChildProcess.proc.on.code (D:\Work\tmp\ws-scrcpy-fix-win\ws-scrcpy-fix-win\node_modules\teen_process\lib\exec.js:113:19)
ERR! ServerDeviceConnection     at ChildProcess.emit (events.js:198:13)
ERR! ServerDeviceConnection     at maybeClose (internal/child_process.js:982:16)
ERR! ServerDeviceConnection     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
ERR! ServerDeviceConnection Error: Command 'D:\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s R38KA0JHAHA shell 'ip route|grep wlan0|grep -v default'' exited with code 1
ERR! ServerDeviceConnection     at ChildProcess.proc.on.code (D:\Work\tmp\ws-scrcpy-fix-win\ws-scrcpy-fix-win\node_modules\teen_process\lib\exec.js:113:19)
ERR! ServerDeviceConnection     at ChildProcess.emit (events.js:198:13)
ERR! ServerDeviceConnection     at maybeClose (internal/child_process.js:982:16)
ERR! ServerDeviceConnection     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

Could you help me for this issue?

**Comment by drauggres** [comment]
Hi.
This command (```adb.exe -P 5037 -s R39KC04P6W shell 'ip route|grep wlan0|grep -v default'```) is used to find the IP address of the device. It is not universal and may fail on some devices.

1. Verify that your device has wifi enabled
2. Check network interface name on the device (`adb shell ifconfig`, or `adb shell 'ip -f inet addr show'`)

**Comment by pdj14** [comment]
Thanks for your checking, with Wifi Connection this is fixed. I will re check and If I met some issue I will update again~ :)
