### ISSUE TITLE
Where can I get api info or documentation.

### ISSUE THREAD

**Issue by tulasikrishan89** [NetrisTV/ws-scrcpy#52]
can you provide api information?
where can i get apk information that stream the jpeg and sends events?

**Comment by drauggres** [comment]
It pretty much the same as original scrcpy: https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md.
The server source code is available here: https://github.com/NetrisTV/scrcpy

**Comment by tulasikrishan89** [comment]
Thanks for the info. I ll check.
