### ISSUE TITLE
Broadway and tinyh264 showing black-screen but functionality is working as normal

### ISSUE THREAD

**Issue by tulasikrishan89** [NetrisTV/ws-scrcpy#53]
Broadway and tinyh264 showing black-screen but functionality like scrolls and swipes work as normal.

Device: Pixel 5
os: Android 11

**Comment by drauggres** [comment]
Hi.
Can you try https://github.com/NetrisTV/ws-scrcpy/issues/25#issuecomment-695804670?
Closing this issue as duplicate.

**Comment by drauggres** [comment]
If you try `profile=1,level=1` make sure you don't have server already running on your device (kill it from browser or manually).
You can verify that these arguments are applied by running: `cat /proc/PID/cmdline` in adb shell, where PID is number from the `Pid` column. The output should contain `profile=1,level=1`, i.e. look smth like this:
```
generic_x86_64:/ # cat /proc/25994/cmdline                                                                                                                                                  
app_process/com.genymobile.scrcpy.Server1.16-ws1ERROR0800000060-1false-falsetrue0falsefalseprofile=1,level=1web8886generic_x86_64:/ #
```
