### ISSUE TITLE
possible to run loading screen while device is still preparing to stream

### ISSUE THREAD

**Issue by tulasikrishan89** [NetrisTV/ws-scrcpy#54]
I see devices are taking time to stream images to ws client. Is it possible to run some kind of loading screen or shimmering in client-ws while screen is not rendering any images

**Comment by drauggres** [comment]
Never had a reason for a loading screen. In my case, there was always less than half a second between page load and first frame.

But if you need, you can create an additional stub-element and place it on top of `touchableCanvas` (or on top of everything in the `<body>`) [here](https://github.com/NetrisTV/ws-scrcpy/blob/master/src/app/decoder/Decoder.ts#L196-L200). And later hide it then decoder is ready to draw the first frame:
- for "canvas-based" decoders look [here](https://github.com/NetrisTV/ws-scrcpy/blob/369c6cf83185c72742224faef24172a1d754e0d5/src/app/decoder/CanvasCommon.ts#L45-L53)
- for mse decoder - [here](https://github.com/NetrisTV/ws-scrcpy/blob/369c6cf83185c72742224faef24172a1d754e0d5/src/app/decoder/MseDecoder.ts#L119-L123)
