### ISSUE TITLE
show touches or tap

### ISSUE THREAD

**Issue by krishtoautomate** [NetrisTV/ws-scrcpy#55]
can you add show touches and tap and change mouse to hand image instead of mouse-pointer

**Comment by drauggres** [comment]
I always enable `Pointer location` in `Developer options`:
<details>
  <summary>Screenshot</summary>

![11 01 2021, 15_22_19](https://user-images.githubusercontent.com/7796592/104182112-ffaac380-5420-11eb-91b8-1bf8e463b4e7.png)
</details>

For "hand image" cursor you can add `cursor: pointer;` here:
https://github.com/NetrisTV/ws-scrcpy/blob/8cc33b86778dae8ef91a3c691c09eac89b5b1e4e/src/style/app.css#L144-L147
I'm fine with the default cursor.

**Comment by krishtoautomate** [comment]
already touch and scroll showing in ios component
