### ISSUE TITLE
where can I find which api is calling touch and sendKey event

### ISSUE THREAD

**Issue by tulasikrishan89** [NetrisTV/ws-scrcpy#56]
can you please point me to right direction in finding functions for touches and tap events to devices

found below info but couldnt find where touch command is sent to device
```javascript
 public sendEvent(e: ControlMessage): void {
        console.log("sendEvent : "+e)
        this.streamReceiver.sendEvent(e);
    }
```
```javascript
 public sendEvent(event: ControlMessage): void {
        if (this.hasConnection()) {
            (this.ws as WebSocket).send(event.toBuffer());
        } else {
            this.events.push(event);
        }
    }
```
Thanks

**Comment by drauggres** [comment]
This is exactly the place where all `ControlMessage`s are sent to a device.
All classes for `ControlMessage`s are here: https://github.com/NetrisTV/ws-scrcpy/tree/master/src/app/controlMessage.

On server side you should look [here](https://github.com/NetrisTV/scrcpy/blob/feature/websocket-v1.16.x/server/src/main/java/com/genymobile/scrcpy/ControlMessage.java) and [here](https://github.com/NetrisTV/scrcpy/blob/feature/websocket-v1.16.x/server/src/main/java/com/genymobile/scrcpy/ControlMessageReader.java).
