### ISSUE TITLE
Strange behavior with unfocused browser tab

### ISSUE THREAD

**Issue by ClaudiuGeorgiu** [NetrisTV/ws-scrcpy#58]
Hi, this tool is working great! However, I noticed a strange behavior when running it in a background tab: the video stream seems to pause when the tab loses focus, and when I open the tab again all the frames are shown very fast until the stream gets back "live" (it's like the frames were buffered while the browser tab was not focused). The following video should clarify what I mean (browser on the left, emulator on the right):

https://user-images.githubusercontent.com/6818578/103784723-969b0880-503a-11eb-9fb5-03e7d0581b8c.mp4

I guess it is related to [this](https://stackoverflow.com/a/6585153/5268548), but I'm not sure. The same behavior happens with both Chrome and Firefox, with all the decoders. I'm using the latest commit on master branch and an Android 11 emulator, everything running on Ubuntu 20.

In case you need further details, let me know, I'll be happy to help.
Thanks!

**Comment by drauggres** [comment]
Hi.
Please try [this branch](https://github.com/NetrisTV/ws-scrcpy/tree/feature/drop_decoded_frames).

**Comment by ClaudiuGeorgiu** [comment]
> Hi.
> Please try [this branch](https://github.com/NetrisTV/ws-scrcpy/tree/feature/drop_decoded_frames).

Thanks! I just tested the new branch and I confirm that now it works correctly without any strange behavior.
