### ISSUE TITLE
Feature request: Toggle for turning off the screen of the local device while continuing to mirror

### ISSUE THREAD

**Issue by kwiksilver** [NetrisTV/ws-scrcpy#65]
The standard scrcpy client has an option to turn the screen off on the device while still streaming the display to the scrcpy app. This is accomplished by using "scrcpy --turn-screen-off" or "scrcpy -S"

I was wondering if that could be something we could configure either as toggle button on the right of the web stream or in one of the config files.

Having the screen off help prevent screen burn in, and reduces heat of the device.

**Comment by drauggres** [comment]
Feature implemented in `v0.7.0-beta2`([`develop`](https://github.com/NetrisTV/ws-scrcpy/tree/develop))
