### ISSUE TITLE
input breaks on remote control if dragging outside the window of the mobile

### ISSUE THREAD

**Issue by vans163** [NetrisTV/ws-scrcpy#66]
If you click and drag holding outside the area of the web render window, the app seems to crash/bug and you need to restart the device itself. No input works until device is restarted.

I think what happens is the drag event never releases.

**Comment by drauggres** [comment]
Hi.

>I think what happens is the drag event never releases.

Yeah, most likely something like that. Does restarting the scrcpy-server help (click on the `PID` in device list to kill and again to start)?

**Comment by vans163** [comment]
> Hi.
> 
> > I think what happens is the drag event never releases.
> 
> Yeah, most likely something like that. Does restarting the scrcpy-server help (click on the `PID` in device list to kill and again to start)?

Let me try this next time, I think it should.

**Comment by drauggres** [comment]
@vans163 can you also check logcat for stacktraces (`adb logcat | grep -i scrcpy`)?

**Comment by drauggres** [comment]
@vans163 Please try [develop](https://github.com/NetrisTV/ws-scrcpy/tree/develop) branch and let me know if problem still exists.

**Comment by vans163** [comment]
@drauggres Killing the scrcpy-server using the panel fixes the issue.  Trying now develop.
