### ISSUE TITLE
can you add keyboard event?

### ISSUE THREAD

**Issue by wan766405890** [NetrisTV/ws-scrcpy#7]
can you add keyboard event listener,so we can input text by ime!

**Comment by drauggres** [comment]
It is not possible to send non-ASCII characters with keyboard events.
Try `develop` branch. It has clipboard support from scrcpy v1.9 (but some things may be broken).

**Comment by wan766405890** [comment]
Original Scrcpy Support Keyboard Event

**Comment by drauggres** [comment]
Are you sure? (https://github.com/Genymobile/scrcpy/issues/37 https://github.com/Genymobile/scrcpy/issues/632). Or do you mean something else?

**Comment by wan766405890** [comment]
what i mean is input text and cut/paste by keyboard directly! I am sure Scrcpy support it!

**Comment by drauggres** [comment]
OK, now I understand what you want. It should be easy to do, but not sure when I could do it.
You can try to implement this yourself, basically you need to:
1. add listeners for `keydown` and `keyup` events
2. create [`KeyCodeControlEvent`](https://github.com/NetrisTV/ws-scrcpy/blob/develop/src/controlEvent/KeyCodeControlEvent.ts) in these listeners
3. call `connection.send(event)` with this `KeyCodeControlEvent` as argument.

Look [here](https://github.com/NetrisTV/ws-scrcpy/blob/develop/src/DeviceController.ts#L176) for example.

P.S. you know that you can type text into input and when press `Send as keys` button, right?

**Comment by wan766405890** [comment]
yes

**Comment by wan766405890** [comment]
Yes,Thank you,i should use emscripten to compile ffmpeg to decoding h246 stream

**Comment by wan766405890** [comment]
Android6.0 Black screen,but control function is enable by develop branch

**Comment by drauggres** [comment]
Please, open separate issues for different problems (also make sure that it is not reproduced in original scrcpy).

**Comment by daigaigai520** [comment]
hi, can you update the version?  
newest scrcpy version is 1.21.1, and TYPE_INJECT_MOUSE_EVENT has been removed.

**Comment by drauggres** [comment]
@daigaigai520 I plan to do it, but no promises. Any help is appreciated and PRs are welcome (scrcpy fork is [here](https://github.com/NetrisTV/scrcpy/tree/feature/websocket-v1.9)).

P.S. Please open separate issues for different problems.
