### ISSUE TITLE
get Connected Device list method information

### ISSUE THREAD

**Issue by tulasikrishan89** [NetrisTV/ws-scrcpy#74]
I would like to know the information which method is pulling device list and adding device list to html page.

Thanks

**Comment by drauggres** [comment]
### Server.
1. Init tracker
https://github.com/NetrisTV/ws-scrcpy/blob/994d4c67394d63ecdf6cfbc51f48c8e71c686e6e/src/server/services/AndroidDeviceTracker.ts#L94-L95
2. Device list changed
https://github.com/NetrisTV/ws-scrcpy/blob/994d4c67394d63ecdf6cfbc51f48c8e71c686e6e/src/server/services/AndroidDeviceTracker.ts#L73-L77
3. Get device list
https://github.com/NetrisTV/ws-scrcpy/blob/994d4c67394d63ecdf6cfbc51f48c8e71c686e6e/src/server/services/AndroidDeviceTracker.ts#L125-L127
4. Send device list to a client
https://github.com/NetrisTV/ws-scrcpy/blob/994d4c67394d63ecdf6cfbc51f48c8e71c686e6e/src/server/mw/DeviceTracker.ts#L34-L42

### Client
https://github.com/NetrisTV/ws-scrcpy/blob/994d4c67394d63ecdf6cfbc51f48c8e71c686e6e/src/app/client/DeviceTrackerDroid.ts#L169

**Comment by tulasikrishan89** [comment]
very helpful. thanks for the info.
