### ISSUE TITLE
New devices are not recognized

### ISSUE THREAD

**Issue by tulasikrishan89** [NetrisTV/ws-scrcpy#76]
<BUG>
When application is built without connecting devices and later if devices are connected, it is not recognizing.

list is : []
after build and send
getDevices: []
buildAndSendMessage: []

***connect new device**
Device tracker is down. Will try to restart in 1000ms

***refresh page**
after build and send
getDevices: []
buildAndSendMessage: []
after build and send
getDevices: []
buildAndSendMessage: []

**Comment by drauggres** [comment]
@tulasikrishan89 please try lastest code from `master` branch
