### ISSUE TITLE
Can't work on android chrome.

### ISSUE THREAD

**Issue by realgtk** [NetrisTV/ws-scrcpy#78]
Android chrome visit http://192.168.10.182:8000/#!action=stream&udid=......, click no response.

**Comment by drauggres** [comment]
Hi. This is probably not related to chrome/android.

Your options:
1. Make sure that you have wifi enabled on the remote device and that your devices are on the same network. You can select network interface of the remote device from main page (and you should see selected IP address in the `ip` argument of the `/#!action=stream` link)
2. Select `proxy over adb` from the network interfaces list

You can also click `Configure stream` instead of the direct player link, to see if you can access a remote device through the selected interface.

**Comment by realgtk** [comment]
![111](https://user-images.githubusercontent.com/6158059/112612881-6a816d80-8e5a-11eb-83f0-5e6e8f7be0ac.png)

The screen of device A can be displayed, but no response when I clicked on device B.

**Comment by drauggres** [comment]
So, you can't control the remote device, right?
You may need to enable [additional option](https://github.com/Genymobile/scrcpy/issues/70#issuecomment-373286323) in the "Developer options".

Does the original scrcpy work with your device?

**Comment by realgtk** [comment]
Chrome on PC: show screen, can control.
Original scrcpy: show screen, can control.
Chrome on Android: show screen, but can't control.

**Comment by drauggres** [comment]
Well, this is strange. I don't have android device with chrome around right now, but it works with the remote one (also controlled via ws-scrcpy). And it also works with old webkit-based browsers and mobile safari.

If you want to try to debug this yourself I can write a short "how-to".

**Comment by drauggres** [comment]
I can not reproduce this issiue. Control works fine on Chrome `89.0.4389.105` on Android `7.1.2`.

**Comment by realgtk** [comment]
It work fine on my iPhone. Thanks!

**Comment by realgtk** [comment]
It works fine on my iPhone. Thanks!

**Comment by drauggres** [comment]
What about chrome/android? Did you manage to fix it or it still does not work?

**Comment by realgtk** [comment]
I only have Huawei P20 and P40, neither of them can work.

**Comment by realgtk** [comment]
I used wireshark to analyze the websocket data and found that only received "ACTION_UP" and "ACTION_MOVE",  no "ACTION_DOWN" message. So I modified TouchControlMessage.ts:
buffer.writeUInt16BE(1 * TouchControlMessage.MAX_PRESSURE_VALUE, offset);
Now it works well!

**Comment by drauggres** [comment]
Can you debug the client? There are two places where `TouchControlMessage` is created:
1. From `TouchEvent`
https://github.com/NetrisTV/ws-scrcpy/blob/deedf293b0699c43a55c344746e03f9272b4a6df/src/app/touchHandler/TouchHandler.ts#L483-L488

2. From `MouseEvent`
https://github.com/NetrisTV/ws-scrcpy/blob/deedf293b0699c43a55c344746e03f9272b4a6df/src/app/touchHandler/TouchHandler.ts#L523-L528

I guess, that you hit the first case, but `touch.force` is invalid. Can you check that?

**Comment by drauggres** [comment]
Probably correct code for the first case should look like this:

```typescript
  let pressure = 1;
  if (action === MotionEvent.ACTION_UP) {
      pressure = 0;
  } else if (typeof touch.force === 'number') {
      pressure = touch.force;
  }
  if (!invalid) {
      const message = new TouchControlMessage(action, pointerId, position, pressure, buttons);
```

**Comment by realgtk** [comment]
> Probably correct code for the first case should look like this:
> 
> ```ts
>   let pressure = 1;
>   if (action === MotionEvent.ACTION_UP) {
>       pressure = 0;
>   } else if (typeof touch.force === 'number') {
>       pressure = touch.force;
>   }
>   if (!invalid) {
>       const message = new TouchControlMessage(action, pointerId, position, pressure, buttons);
> ```

Test OK, thanks!
