### ISSUE TITLE
[ws-qvh] Where is calculating mouse x and mouse y for tap or swipe?

### ISSUE THREAD

**Issue by tulasikrishan89** [NetrisTV/ws-scrcpy#79]
can you please point me in code where the mouse x and mouse y are calculated on canvas when performing click xy.

Thanks

**Comment by drauggres** [comment]
From here:
https://github.com/NetrisTV/ws-scrcpy/blob/239600348ea3d1b43b021aacf7fde40d008618ed/src/app/touchHandler/SimpleTouchHandler.ts#L33

to here:
https://github.com/NetrisTV/ws-scrcpy/blob/239600348ea3d1b43b021aacf7fde40d008618ed/src/app/touchHandler/TouchHandler.ts#L506-L512

to here:
https://github.com/NetrisTV/ws-scrcpy/blob/239600348ea3d1b43b021aacf7fde40d008618ed/src/app/touchHandler/TouchHandler.ts#L321-L327

to actual calculations:
https://github.com/NetrisTV/ws-scrcpy/blob/239600348ea3d1b43b021aacf7fde40d008618ed/src/app/touchHandler/TouchHandler.ts#L207-L264

**Comment by tulasikrishan89** [comment]
Very helpful thanks
