### ISSUE TITLE
[ws-qvh] how to change video setting for iOS

### ISSUE THREAD

**Issue by donmezburak** [NetrisTV/ws-scrcpy#81]
Hi, I want to change video settings for iOS.

I am using ws-qvh project also. I changed bitrate and maxfps values on MsePlayerForQVHack class. However it does not change anything. How can I edit video settings ? 

Thanks.

**Comment by drauggres** [comment]
Hello.

There is no way to change any video settings for iOS: https://github.com/danielpaulus/quicktime_video_hack/issues/81

It is be possible to use gstreamer with [`quicktime video hack`](https://github.com/danielpaulus/quicktime_video_hack) to transcode video with the desired parameters, but I have not implemented that in ws-qvh.

**Comment by donmezburak** [comment]
thanks, I will check it out. if I do in ws-qvh, i will open a pull-request.
