### ISSUE TITLE
no video stream data receive

### ISSUE THREAD

**Issue by HOTTIN** [NetrisTV/ws-scrcpy#83]
when i connect to the socket, i can receive the first 155 bytelength data, and it is equal to `stringToUtf8ByteArray('scrcpy_initial')`,
but after that i receive no more data... my using version is 1.17-ws5, do i need to emit some cmd message to start video transfer?
Hope you could help me～
![image](https://user-images.githubusercontent.com/12428754/113824376-4a36a480-97b2-11eb-8fea-0a3cc41c4f7b.png)

**Comment by drauggres** [comment]
Hi.

You need to send video settings to the server:
https://github.com/NetrisTV/ws-scrcpy/blob/deedf293b0699c43a55c344746e03f9272b4a6df/src/app/client/StreamClientScrcpy.ts#L179

This command is used to join the stream, later same command can be used to change current video settings.

**Comment by HOTTIN** [comment]
thank you very much!

**Comment by eaphone** [comment]
@drauggres  hi, I am facing the same problem at latest version. 

websocket connect to ws://localhost:8000/?action=proxy-adb&remote=tcp%3A8886&udid=a1b2c3d4 only response a single binary data then stop, either close or error, but no further stream data receive.

This [ws-scrcpy/src/app/client/StreamClientScrcpy.ts] file you quoted above is no longer used and i can not find simliar process at other files. 

could you help me out here?

**Comment by eaphone** [comment]
> @drauggres hi, I am facing the same problem at latest version.
> 
> websocket connect to ws://localhost:8000/?action=proxy-adb&remote=tcp%3A8886&udid=a1b2c3d4 only response a single binary data then stop, either close or error, but no further stream data receive.
> 
> This [ws-scrcpy/src/app/client/StreamClientScrcpy.ts] file you quoted above is no longer used and i can not find simliar process at other files.
> 
> could you help me out here?

oh, i found it. it is sperated to appl and gool type. i will try this. and get back to you if any problem
