### ISSUE TITLE
File push does not work in Safari

### ISSUE THREAD

**Issue by donmezburak** [NetrisTV/ws-scrcpy#84]
Hello,

I saw InstallCommand class but it never used. How can I activate it if user drops and file ? 

Note: Also I realized that 
`const { type, name } = file;` in FilePushHandler.ts line 168 code does not give type due to File interface does not have type.

**Comment by drauggres** [comment]
Hi.

> I saw InstallCommand class but it never used. How can I activate it if user drops and file ?

You can only install apk manually from included xterm shell.
`InstallCommand` is a part of [DeviceFarmer/adbkit](https://github.com/DeviceFarmer/adbkit) and is not used here. File push implemented separately in the [server](https://github.com/NetrisTV/scrcpy/blob/6b510b71a8433ad15f17318c7ad78b1619959af0/server/src/main/java/com/genymobile/scrcpy/FilePushHandler.java) (it is not "`adb push`").

> Note: Also I realized that
> `const { type, name } = file;` in FilePushHandler.ts line 168 code does not give type due to File interface does not have type.

`type` field on `File` is inherited from `Blob` ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/File/type))
```typescript

/** A file-like object of immutable, raw data. Blobs represent data that isn't necessarily in a JavaScript-native format. The File interface is based on Blob, inheriting blob functionality and expanding it to support files on the user's system. */
interface Blob {
    readonly size: number;
    readonly type: string;
    arrayBuffer(): Promise<ArrayBuffer>;
    slice(start?: number, end?: number, contentType?: string): Blob;
    stream(): ReadableStream;
    text(): Promise<string>;
}

declare var Blob: {
    prototype: Blob;
    new(blobParts?: BlobPart[], options?: BlobPropertyBag): Blob;
};

/** Provides information about files and allows JavaScript in a web page to access their content. */
interface File extends Blob {
    readonly lastModified: number;
    readonly name: string;
}
```

**Comment by donmezburak** [comment]
Thanks I will use xterm for installing.

When I drop apk file, it gives not supported file error and type is null.

**Comment by drauggres** [comment]
> When I drop apk file, it gives not supported file error and type is null.

What browser/OS are you using?

**Comment by donmezburak** [comment]
safari Version 14.0.3 (16610.4.3.1.4) on Mac Big Sur 11.2.2 (20D80)

**Comment by drauggres** [comment]
Yeah, on safari I receive empty string as `type` for apk-files.
Will add workaround for safari later.

**Comment by drauggres** [comment]
Workaround for empty `type` added into `master`. But file push still does not work in safari.

**Comment by drauggres** [comment]
Upload fixed in `master`. Verified on Safari 14.1.

Known issue:
* On Safari file upload does not show progress (it works in one piece).
