### ISSUE TITLE
Dragging inward triggers screen events

### ISSUE THREAD

**Issue by direwolf512** [NetrisTV/ws-scrcpy#85]
Hi

When I click the mouse outside the screen and keep it clicked, and then move to the inside of the screen, the screen changes as the mouse moves.

I am using drag and drop components to achieve a zoom function, everything is normal when I drag it out to make it larger, but it will trigger drag events in the screen when I shrink.

How can I prevent screen events from triggering when the mouse moves into the screen area after being clicked outside?

Thanks

**Comment by drauggres** [comment]
Hi.
I implemented it intentionally (#67), so it is possible to do "swipe from edge" gesture without aming into the border.

> How can I prevent screen events from triggering when the mouse moves into the screen area after being clicked outside?

Emulated `ACTION_DOWN` event is generated here (lines 296-298):
https://github.com/NetrisTV/ws-scrcpy/blob/deedf293b0699c43a55c344746e03f9272b4a6df/src/app/touchHandler/TouchHandler.ts#L289-L300

There is no API to disable this feature at the moment, but it is easy to implement.

> I am using drag and drop components to achieve a zoom function, everything is normal when I drag it out to make it larger, but it will trigger drag events in the screen when I shrink.

I didn't quite understand this part.

**Comment by direwolf512** [comment]
> I am using drag and drop components to achieve a zoom function, everything is normal when I drag it out to make it larger, but it will trigger drag events in the screen when I shrink.

I mean, I put the screen in a box. I want to zoom the screen by changing the size of the box. 

But when I reduced the size of the box, I wondered if the 'touch-layer' still maintained its original size because the size of the screen had not changed.

It mistakenly thought that my mouse had entered the screen area and triggered the screening event.
