### ISSUE TITLE
balck border appeared occasionlly

### ISSUE THREAD

**Issue by HOTTIN** [NetrisTV/ws-scrcpy#86]
I`m using the latest version 1.17-ws5, and i got some problem below, I have read some code, and I try to solve it.
could you please tell me is this code ok for you?

![2021-04-16 12-12-49屏幕截图](https://user-images.githubusercontent.com/12428754/114970546-3a534a80-9ead-11eb-965a-34bfdded00ed.png)
![2021-04-16 12-13-33屏幕截图](https://user-images.githubusercontent.com/12428754/114970551-3d4e3b00-9ead-11eb-90f1-34cf591099d5.png)

https://github.com/NetrisTV/scrcpy/blob/6b510b71a8433ad15f17318c7ad78b1619959af0/server/src/main/java/com/genymobile/scrcpy/ScreenInfo.java#L112-L141

i would like to modify code here like this:
``` 
private static Size computeVideoSize(int w, int h, Size bounds) {
        // Compute the video size and the padding of the content inside this video.
        // Principle:
        // - scale down the great side of the screen to maxSize (if necessary);
        // - scale down the other side so that the aspect ratio is preserved;
        // - round this value to the nearest multiple of 8 (H.264 only accepts multiples of 8)
        w &= ~7; // in case it's not a multiple of 8
        h &= ~7;
        if (bounds == null) {
            return new Size(w, h);
        }
        int boundsWidth = bounds.getWidth();
        int boundsHeight = bounds.getHeight();
        if (w > boundsWidth) {
            int minorExactH = h * boundsWidth / w;
            // +4 to round the value to the nearest multiple of 8
            h = (minorExactH + 4) & ~7;
            w = boundsWidth;
        }
        if (h > boundsHeight) {
            int minorExactW = w * boundsHeight / h;
            // +4 to round the value to the nearest multiple of 8
            w = (minorExactW + 4) & ~7;
            h = boundsHeight;
        }
 
        return new Size(w, h);
    }
```

and https://github.com/NetrisTV/scrcpy/blob/6b510b71a8433ad15f17318c7ad78b1619959af0/server/src/main/java/com/genymobile/scrcpy/VideoSettings.java#L92
```
 public void setBounds(int width, int height) {
        this.bounds = new Size(width & ~7, height & ~7); // multiple of 8
}
```
reference：
https://github.com/Genymobile/scrcpy/blob/07a85b7c94fc519c4950a12d7c992f51117b7e81/server/src/main/java/com/genymobile/scrcpy/ScreenInfo.java#L107-L132

**Comment by drauggres** [comment]
Hi.

I changed it to `~15` for a reason.
<details>
  <summary>Screenshot</summary>
  
![mult7](https://user-images.githubusercontent.com/7796592/114987508-eb51e900-9e9d-11eb-9eb3-e38d42fc677b.png)
</details>

You are free to fork both repositories and make any changes you want (there are few `~15` in the client also).

**Comment by HOTTIN** [comment]
OK, thank you very much~
