### ISSUE TITLE
Possible to get droid_device_list in json format with api to localhost:8000/droid_device_list

### ISSUE THREAD

**Issue by tulasikrishan89** [NetrisTV/ws-scrcpy#89]
Possible to get droid_device_list in json format with api to localhost:8000/droid_device_list

It will help to run the application in multiple machine and control with single client

*same information shown in http://localhost:3000, to be displayed in json response of localhost:8000/droid_device_list, including UDID, deviceName, port, href_urls to different video sources, device status etc

**Comment by drauggres** [comment]
> run the application in multiple machine and control with single client

I'm working on it (https://github.com/NetrisTV/ws-scrcpy/compare/develop)

**Comment by tulasikrishan89** [comment]
thanks for Quick reply and action. Please let me know, when can I test this part.

**Comment by tulasikrishan89** [comment]
worked. perfect

connect to socket and get data 

// const ws = new WebSocket(`ws://HOST_URL:8000/?action=appl-device-list`);
// const ws = new WebSocket(`ws://HOST_URL:8000/?action=goog-device-list`);

Thank you so much. it helps to connect to different host and get data of connected device list.
