### ISSUE TITLE
Possible to share developer notes of how scrcpy works

### ISSUE THREAD

**Issue by tulasikrishan89** [NetrisTV/ws-scrcpy#96]
scrcpy forwarding video is port in h264 format is understood. didn't get how touches are sent --

Which method or api is sending touches.
is touches sent to same that connect adb?
Which request body the scrcpy jar accepts for touch or keyboard commands.

Thank you

**Comment by tulasikrishan89** [comment]
if i use proxy over adb.
how touches are video buffer are communicated between device and computer?

**Comment by drauggres** [comment]
1. browser connects to the node.js server
2. server forwards port from device to localhost (same as `adb forward tcp:<FREE_FORT> tcp:8886`)
3. server creates proxy connection between browser and forwarded port

https://github.com/NetrisTV/ws-scrcpy/blob/67cc51c90861cadd1f977f14bc3efe8b5dfa56ca/src/server/goog-device/mw/WebsocketProxyOverAdb.ts#L49-L54

The rest is the same as with a direct connection.
