### ISSUE TITLE
Requires ws-qvh available in PATH.

### ISSUE THREAD

**Issue by krishtoautomate** [NetrisTV/ws-scrcpy#99]
can you please provide example where I should add qs-qvh path?

**Comment by drauggres** [comment]
It should be available via system environment variable `PATH`.
You need to copy `ws-qvh` binary to one of the directories specified in the `PATH` or edit your `PATH` and add directory with `ws-qvh` into it.

https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them
